// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reviewpad/api/go/services (interfaces: HostClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod --destination services_mocks/host_service.go --package services_mocks github.com/reviewpad/api/go/services HostClient
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/reviewpad/api/go/services"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockHostClient is a mock of HostClient interface.
type MockHostClient struct {
	ctrl     *gomock.Controller
	recorder *MockHostClientMockRecorder
	isgomock struct{}
}

// MockHostClientMockRecorder is the mock recorder for MockHostClient.
type MockHostClientMockRecorder struct {
	mock *MockHostClient
}

// NewMockHostClient creates a new mock instance.
func NewMockHostClient(ctrl *gomock.Controller) *MockHostClient {
	mock := &MockHostClient{ctrl: ctrl}
	mock.recorder = &MockHostClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHostClient) EXPECT() *MockHostClientMockRecorder {
	return m.recorder
}

// GetPullRequest mocks base method.
func (m *MockHostClient) GetPullRequest(ctx context.Context, in *services.GetPullRequestRequest, opts ...grpc.CallOption) (*services.GetPullRequestReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPullRequest", varargs...)
	ret0, _ := ret[0].(*services.GetPullRequestReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequest indicates an expected call of GetPullRequest.
func (mr *MockHostClientMockRecorder) GetPullRequest(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequest", reflect.TypeOf((*MockHostClient)(nil).GetPullRequest), varargs...)
}

// GetPullRequestFiles mocks base method.
func (m *MockHostClient) GetPullRequestFiles(ctx context.Context, in *services.GetPullRequestFilesRequest, opts ...grpc.CallOption) (*services.GetPullRequestFilesReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetPullRequestFiles", varargs...)
	ret0, _ := ret[0].(*services.GetPullRequestFilesReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPullRequestFiles indicates an expected call of GetPullRequestFiles.
func (mr *MockHostClientMockRecorder) GetPullRequestFiles(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPullRequestFiles", reflect.TypeOf((*MockHostClient)(nil).GetPullRequestFiles), varargs...)
}

// PostDiffComment mocks base method.
func (m *MockHostClient) PostDiffComment(ctx context.Context, in *services.PostDiffCommentRequest, opts ...grpc.CallOption) (*services.PostDiffCommentReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostDiffComment", varargs...)
	ret0, _ := ret[0].(*services.PostDiffCommentReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostDiffComment indicates an expected call of PostDiffComment.
func (mr *MockHostClientMockRecorder) PostDiffComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostDiffComment", reflect.TypeOf((*MockHostClient)(nil).PostDiffComment), varargs...)
}

// PostGeneralComment mocks base method.
func (m *MockHostClient) PostGeneralComment(ctx context.Context, in *services.PostGeneralCommentRequest, opts ...grpc.CallOption) (*services.PostGeneralCommentReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostGeneralComment", varargs...)
	ret0, _ := ret[0].(*services.PostGeneralCommentReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostGeneralComment indicates an expected call of PostGeneralComment.
func (mr *MockHostClientMockRecorder) PostGeneralComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostGeneralComment", reflect.TypeOf((*MockHostClient)(nil).PostGeneralComment), varargs...)
}

// ReplyDiffComment mocks base method.
func (m *MockHostClient) ReplyDiffComment(ctx context.Context, in *services.ReplyDiffCommentRequest, opts ...grpc.CallOption) (*services.ReplyDiffCommentReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ReplyDiffComment", varargs...)
	ret0, _ := ret[0].(*services.ReplyDiffCommentReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplyDiffComment indicates an expected call of ReplyDiffComment.
func (mr *MockHostClientMockRecorder) ReplyDiffComment(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplyDiffComment", reflect.TypeOf((*MockHostClient)(nil).ReplyDiffComment), varargs...)
}

// SubmitUserReview mocks base method.
func (m *MockHostClient) SubmitUserReview(ctx context.Context, in *services.SubmitUserReviewRequest, opts ...grpc.CallOption) (*services.SubmitUserReviewReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubmitUserReview", varargs...)
	ret0, _ := ret[0].(*services.SubmitUserReviewReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubmitUserReview indicates an expected call of SubmitUserReview.
func (mr *MockHostClientMockRecorder) SubmitUserReview(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmitUserReview", reflect.TypeOf((*MockHostClient)(nil).SubmitUserReview), varargs...)
}
