// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reviewpad/api/go/services (interfaces: RobinClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod --destination services_mocks/robin_service.go --package services_mocks github.com/reviewpad/api/go/services RobinClient
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/reviewpad/api/go/services"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockRobinClient is a mock of RobinClient interface.
type MockRobinClient struct {
	ctrl     *gomock.Controller
	recorder *MockRobinClientMockRecorder
	isgomock struct{}
}

// MockRobinClientMockRecorder is the mock recorder for MockRobinClient.
type MockRobinClientMockRecorder struct {
	mock *MockRobinClient
}

// NewMockRobinClient creates a new mock instance.
func NewMockRobinClient(ctrl *gomock.Controller) *MockRobinClient {
	mock := &MockRobinClient{ctrl: ctrl}
	mock.recorder = &MockRobinClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRobinClient) EXPECT() *MockRobinClientMockRecorder {
	return m.recorder
}

// ChatInCodeHost mocks base method.
func (m *MockRobinClient) ChatInCodeHost(ctx context.Context, in *services.ChatInCodeHostRequest, opts ...grpc.CallOption) (*services.ChatInCodeHostReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChatInCodeHost", varargs...)
	ret0, _ := ret[0].(*services.ChatInCodeHostReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatInCodeHost indicates an expected call of ChatInCodeHost.
func (mr *MockRobinClientMockRecorder) ChatInCodeHost(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatInCodeHost", reflect.TypeOf((*MockRobinClient)(nil).ChatInCodeHost), varargs...)
}

// Explain mocks base method.
func (m *MockRobinClient) Explain(ctx context.Context, in *services.ExplainRequest, opts ...grpc.CallOption) (*services.ExplainReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Explain", varargs...)
	ret0, _ := ret[0].(*services.ExplainReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Explain indicates an expected call of Explain.
func (mr *MockRobinClientMockRecorder) Explain(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explain", reflect.TypeOf((*MockRobinClient)(nil).Explain), varargs...)
}

// Prompt mocks base method.
func (m *MockRobinClient) Prompt(ctx context.Context, in *services.PromptRequest, opts ...grpc.CallOption) (*services.PromptReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Prompt", varargs...)
	ret0, _ := ret[0].(*services.PromptReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prompt indicates an expected call of Prompt.
func (mr *MockRobinClientMockRecorder) Prompt(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prompt", reflect.TypeOf((*MockRobinClient)(nil).Prompt), varargs...)
}

// RawPrompt mocks base method.
func (m *MockRobinClient) RawPrompt(ctx context.Context, in *services.RawPromptRequest, opts ...grpc.CallOption) (*services.PromptReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RawPrompt", varargs...)
	ret0, _ := ret[0].(*services.PromptReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RawPrompt indicates an expected call of RawPrompt.
func (mr *MockRobinClientMockRecorder) RawPrompt(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawPrompt", reflect.TypeOf((*MockRobinClient)(nil).RawPrompt), varargs...)
}

// Summarize mocks base method.
func (m *MockRobinClient) Summarize(ctx context.Context, in *services.SummarizeRequest, opts ...grpc.CallOption) (*services.SummarizeReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Summarize", varargs...)
	ret0, _ := ret[0].(*services.SummarizeReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Summarize indicates an expected call of Summarize.
func (mr *MockRobinClientMockRecorder) Summarize(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Summarize", reflect.TypeOf((*MockRobinClient)(nil).Summarize), varargs...)
}
