// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/reviewpad/api/go/services (interfaces: SemanticClient)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod --destination services_mocks/semantic_service.go --package services_mocks github.com/reviewpad/api/go/services SemanticClient
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	context "context"
	reflect "reflect"

	services "github.com/reviewpad/api/go/services"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSemanticClient is a mock of SemanticClient interface.
type MockSemanticClient struct {
	ctrl     *gomock.Controller
	recorder *MockSemanticClientMockRecorder
	isgomock struct{}
}

// MockSemanticClientMockRecorder is the mock recorder for MockSemanticClient.
type MockSemanticClientMockRecorder struct {
	mock *MockSemanticClient
}

// NewMockSemanticClient creates a new mock instance.
func NewMockSemanticClient(ctrl *gomock.Controller) *MockSemanticClient {
	mock := &MockSemanticClient{ctrl: ctrl}
	mock.recorder = &MockSemanticClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSemanticClient) EXPECT() *MockSemanticClientMockRecorder {
	return m.recorder
}

// GetSymbols mocks base method.
func (m *MockSemanticClient) GetSymbols(ctx context.Context, in *services.GetSymbolsRequest, opts ...grpc.CallOption) (*services.GetSymbolsReply, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSymbols", varargs...)
	ret0, _ := ret[0].(*services.GetSymbolsReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSymbols indicates an expected call of GetSymbols.
func (mr *MockSemanticClientMockRecorder) GetSymbols(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSymbols", reflect.TypeOf((*MockSemanticClient)(nil).GetSymbols), varargs...)
}
