// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: codehost/branch.proto

package codehost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Branch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sha           string                 `protobuf:"bytes,2,opt,name=sha,proto3" json:"sha,omitempty"`
	Repo          *Repository            `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Branch) Reset() {
	*x = Branch{}
	mi := &file_codehost_branch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Branch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Branch) ProtoMessage() {}

func (x *Branch) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_branch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Branch.ProtoReflect.Descriptor instead.
func (*Branch) Descriptor() ([]byte, []int) {
	return file_codehost_branch_proto_rawDescGZIP(), []int{0}
}

func (x *Branch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Branch) GetSha() string {
	if x != nil {
		return x.Sha
	}
	return ""
}

func (x *Branch) GetRepo() *Repository {
	if x != nil {
		return x.Repo
	}
	return nil
}

var File_codehost_branch_proto protoreflect.FileDescriptor

const file_codehost_branch_proto_rawDesc = "" +
	"\n" +
	"\x15codehost/branch.proto\x12\bcodehost\x1a\x19codehost/repository.proto\"X\n" +
	"\x06Branch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03sha\x18\x02 \x01(\tR\x03sha\x12(\n" +
	"\x04repo\x18\x03 \x01(\v2\x14.codehost.RepositoryR\x04repoB&Z$github.com/reviewpad/api/go/codehostb\x06proto3"

var (
	file_codehost_branch_proto_rawDescOnce sync.Once
	file_codehost_branch_proto_rawDescData []byte
)

func file_codehost_branch_proto_rawDescGZIP() []byte {
	file_codehost_branch_proto_rawDescOnce.Do(func() {
		file_codehost_branch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codehost_branch_proto_rawDesc), len(file_codehost_branch_proto_rawDesc)))
	})
	return file_codehost_branch_proto_rawDescData
}

var file_codehost_branch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_codehost_branch_proto_goTypes = []any{
	(*Branch)(nil),     // 0: codehost.Branch
	(*Repository)(nil), // 1: codehost.Repository
}
var file_codehost_branch_proto_depIdxs = []int32{
	1, // 0: codehost.Branch.repo:type_name -> codehost.Repository
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codehost_branch_proto_init() }
func file_codehost_branch_proto_init() {
	if File_codehost_branch_proto != nil {
		return
	}
	file_codehost_repository_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codehost_branch_proto_rawDesc), len(file_codehost_branch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codehost_branch_proto_goTypes,
		DependencyIndexes: file_codehost_branch_proto_depIdxs,
		MessageInfos:      file_codehost_branch_proto_msgTypes,
	}.Build()
	File_codehost_branch_proto = out.File
	file_codehost_branch_proto_goTypes = nil
	file_codehost_branch_proto_depIdxs = nil
}
