// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: codehost/code_review.proto

package codehost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReviewStatus int32

const (
	UserReviewStatus_USER_REQUESTED_CHANGES UserReviewStatus = 0
	UserReviewStatus_USER_APPROVED          UserReviewStatus = 1
	UserReviewStatus_USER_COMMENTED         UserReviewStatus = 2
	UserReviewStatus_PENDING                UserReviewStatus = 3
	UserReviewStatus_DISMISSED              UserReviewStatus = 4
)

// Enum value maps for UserReviewStatus.
var (
	UserReviewStatus_name = map[int32]string{
		0: "USER_REQUESTED_CHANGES",
		1: "USER_APPROVED",
		2: "USER_COMMENTED",
		3: "PENDING",
		4: "DISMISSED",
	}
	UserReviewStatus_value = map[string]int32{
		"USER_REQUESTED_CHANGES": 0,
		"USER_APPROVED":          1,
		"USER_COMMENTED":         2,
		"PENDING":                3,
		"DISMISSED":              4,
	}
)

func (x UserReviewStatus) Enum() *UserReviewStatus {
	p := new(UserReviewStatus)
	*p = x
	return p
}

func (x UserReviewStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserReviewStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_code_review_proto_enumTypes[0].Descriptor()
}

func (UserReviewStatus) Type() protoreflect.EnumType {
	return &file_codehost_code_review_proto_enumTypes[0]
}

func (x UserReviewStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserReviewStatus.Descriptor instead.
func (UserReviewStatus) EnumDescriptor() ([]byte, []int) {
	return file_codehost_code_review_proto_rawDescGZIP(), []int{0}
}

type ReviewEvent int32

const (
	ReviewEvent_APPROVE         ReviewEvent = 0
	ReviewEvent_REQUEST_CHANGES ReviewEvent = 1
	ReviewEvent_COMMENT         ReviewEvent = 2
	ReviewEvent_UNAPPROVE       ReviewEvent = 3
)

// Enum value maps for ReviewEvent.
var (
	ReviewEvent_name = map[int32]string{
		0: "APPROVE",
		1: "REQUEST_CHANGES",
		2: "COMMENT",
		3: "UNAPPROVE",
	}
	ReviewEvent_value = map[string]int32{
		"APPROVE":         0,
		"REQUEST_CHANGES": 1,
		"COMMENT":         2,
		"UNAPPROVE":       3,
	}
)

func (x ReviewEvent) Enum() *ReviewEvent {
	p := new(ReviewEvent)
	*p = x
	return p
}

func (x ReviewEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_code_review_proto_enumTypes[1].Descriptor()
}

func (ReviewEvent) Type() protoreflect.EnumType {
	return &file_codehost_code_review_proto_enumTypes[1]
}

func (x ReviewEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewEvent.Descriptor instead.
func (ReviewEvent) EnumDescriptor() ([]byte, []int) {
	return file_codehost_code_review_proto_rawDescGZIP(), []int{1}
}

type UserReview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReviewerId    string                 `protobuf:"bytes,2,opt,name=reviewer_id,json=reviewerId,proto3" json:"reviewer_id,omitempty"`
	BaseCommitId  string                 `protobuf:"bytes,3,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	HeadCommitId  string                 `protobuf:"bytes,4,opt,name=head_commit_id,json=headCommitId,proto3" json:"head_commit_id,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Status        UserReviewStatus       `protobuf:"varint,6,opt,name=status,proto3,enum=codehost.UserReviewStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExternalId    string                 `protobuf:"bytes,9,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReview) Reset() {
	*x = UserReview{}
	mi := &file_codehost_code_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReview) ProtoMessage() {}

func (x *UserReview) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_code_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReview.ProtoReflect.Descriptor instead.
func (*UserReview) Descriptor() ([]byte, []int) {
	return file_codehost_code_review_proto_rawDescGZIP(), []int{0}
}

func (x *UserReview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserReview) GetReviewerId() string {
	if x != nil {
		return x.ReviewerId
	}
	return ""
}

func (x *UserReview) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *UserReview) GetHeadCommitId() string {
	if x != nil {
		return x.HeadCommitId
	}
	return ""
}

func (x *UserReview) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *UserReview) GetStatus() UserReviewStatus {
	if x != nil {
		return x.Status
	}
	return UserReviewStatus_USER_REQUESTED_CHANGES
}

func (x *UserReview) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserReview) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserReview) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

var File_codehost_code_review_proto protoreflect.FileDescriptor

const file_codehost_code_review_proto_rawDesc = "" +
	"\n" +
	"\x1acodehost/code_review.proto\x12\bcodehost\"\xb0\x02\n" +
	"\n" +
	"UserReview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreviewer_id\x18\x02 \x01(\tR\n" +
	"reviewerId\x12$\n" +
	"\x0ebase_commit_id\x18\x03 \x01(\tR\fbaseCommitId\x12$\n" +
	"\x0ehead_commit_id\x18\x04 \x01(\tR\fheadCommitId\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x122\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1a.codehost.UserReviewStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\x1f\n" +
	"\vexternal_id\x18\t \x01(\tR\n" +
	"externalId*q\n" +
	"\x10UserReviewStatus\x12\x1a\n" +
	"\x16USER_REQUESTED_CHANGES\x10\x00\x12\x11\n" +
	"\rUSER_APPROVED\x10\x01\x12\x12\n" +
	"\x0eUSER_COMMENTED\x10\x02\x12\v\n" +
	"\aPENDING\x10\x03\x12\r\n" +
	"\tDISMISSED\x10\x04*K\n" +
	"\vReviewEvent\x12\v\n" +
	"\aAPPROVE\x10\x00\x12\x13\n" +
	"\x0fREQUEST_CHANGES\x10\x01\x12\v\n" +
	"\aCOMMENT\x10\x02\x12\r\n" +
	"\tUNAPPROVE\x10\x03B&Z$github.com/reviewpad/api/go/codehostb\x06proto3"

var (
	file_codehost_code_review_proto_rawDescOnce sync.Once
	file_codehost_code_review_proto_rawDescData []byte
)

func file_codehost_code_review_proto_rawDescGZIP() []byte {
	file_codehost_code_review_proto_rawDescOnce.Do(func() {
		file_codehost_code_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codehost_code_review_proto_rawDesc), len(file_codehost_code_review_proto_rawDesc)))
	})
	return file_codehost_code_review_proto_rawDescData
}

var file_codehost_code_review_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_codehost_code_review_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_codehost_code_review_proto_goTypes = []any{
	(UserReviewStatus)(0), // 0: codehost.UserReviewStatus
	(ReviewEvent)(0),      // 1: codehost.ReviewEvent
	(*UserReview)(nil),    // 2: codehost.UserReview
}
var file_codehost_code_review_proto_depIdxs = []int32{
	0, // 0: codehost.UserReview.status:type_name -> codehost.UserReviewStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codehost_code_review_proto_init() }
func file_codehost_code_review_proto_init() {
	if File_codehost_code_review_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codehost_code_review_proto_rawDesc), len(file_codehost_code_review_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codehost_code_review_proto_goTypes,
		DependencyIndexes: file_codehost_code_review_proto_depIdxs,
		EnumInfos:         file_codehost_code_review_proto_enumTypes,
		MessageInfos:      file_codehost_code_review_proto_msgTypes,
	}.Build()
	File_codehost_code_review_proto = out.File
	file_codehost_code_review_proto_goTypes = nil
	file_codehost_code_review_proto_depIdxs = nil
}
