// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: codehost/comment.proto

package codehost

import (
	entities "github.com/reviewpad/api/go/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommentSeverity int32

const (
	CommentSeverity_LOW    CommentSeverity = 0
	CommentSeverity_MEDIUM CommentSeverity = 1
	CommentSeverity_HIGH   CommentSeverity = 2
)

// Enum value maps for CommentSeverity.
var (
	CommentSeverity_name = map[int32]string{
		0: "LOW",
		1: "MEDIUM",
		2: "HIGH",
	}
	CommentSeverity_value = map[string]int32{
		"LOW":    0,
		"MEDIUM": 1,
		"HIGH":   2,
	}
)

func (x CommentSeverity) Enum() *CommentSeverity {
	p := new(CommentSeverity)
	*p = x
	return p
}

func (x CommentSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_comment_proto_enumTypes[0].Descriptor()
}

func (CommentSeverity) Type() protoreflect.EnumType {
	return &file_codehost_comment_proto_enumTypes[0]
}

func (x CommentSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentSeverity.Descriptor instead.
func (CommentSeverity) EnumDescriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{0}
}

type CommentType int32

const (
	CommentType_UNKNOWN CommentType = 0
	CommentType_DIFF    CommentType = 1
	CommentType_GENERAL CommentType = 2
)

// Enum value maps for CommentType.
var (
	CommentType_name = map[int32]string{
		0: "UNKNOWN",
		1: "DIFF",
		2: "GENERAL",
	}
	CommentType_value = map[string]int32{
		"UNKNOWN": 0,
		"DIFF":    1,
		"GENERAL": 2,
	}
)

func (x CommentType) Enum() *CommentType {
	p := new(CommentType)
	*p = x
	return p
}

func (x CommentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentType) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_comment_proto_enumTypes[1].Descriptor()
}

func (CommentType) Type() protoreflect.EnumType {
	return &file_codehost_comment_proto_enumTypes[1]
}

func (x CommentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentType.Descriptor instead.
func (CommentType) EnumDescriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{1}
}

type CommentLineType int32

const (
	CommentLineType_LINE_ADDED   CommentLineType = 0
	CommentLineType_LINE_REMOVED CommentLineType = 1
	CommentLineType_CONTEXT_LINE CommentLineType = 2
)

// Enum value maps for CommentLineType.
var (
	CommentLineType_name = map[int32]string{
		0: "LINE_ADDED",
		1: "LINE_REMOVED",
		2: "CONTEXT_LINE",
	}
	CommentLineType_value = map[string]int32{
		"LINE_ADDED":   0,
		"LINE_REMOVED": 1,
		"CONTEXT_LINE": 2,
	}
)

func (x CommentLineType) Enum() *CommentLineType {
	p := new(CommentLineType)
	*p = x
	return p
}

func (x CommentLineType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentLineType) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_comment_proto_enumTypes[2].Descriptor()
}

func (CommentLineType) Type() protoreflect.EnumType {
	return &file_codehost_comment_proto_enumTypes[2]
}

func (x CommentLineType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentLineType.Descriptor instead.
func (CommentLineType) EnumDescriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{2}
}

type ReviewComment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// In GitLab / Bitbucket, you can have threads in the general comments
	ReplyTo      string                 `protobuf:"bytes,2,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`
	Author       *User                  `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Severity     CommentSeverity        `protobuf:"varint,4,opt,name=severity,proto3,enum=codehost.CommentSeverity" json:"severity,omitempty"`
	Body         string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	CodeReviewId string                 `protobuf:"bytes,6,opt,name=code_review_id,json=codeReviewId,proto3" json:"code_review_id,omitempty"`
	UserId       string                 `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserReviewId string                 `protobuf:"bytes,8,opt,name=user_review_id,json=userReviewId,proto3" json:"user_review_id,omitempty"`
	Location     *ReviewCommentLocation `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Resolved     *bool                  `protobuf:"varint,10,opt,name=resolved,proto3,oneof" json:"resolved,omitempty"`
	Type         CommentType            `protobuf:"varint,11,opt,name=type,proto3,enum=codehost.CommentType" json:"type,omitempty"`
	IsOutdated   bool                   `protobuf:"varint,12,opt,name=is_outdated,json=isOutdated,proto3" json:"is_outdated,omitempty"`
	Context      *entities.ChangesBlock `protobuf:"bytes,13,opt,name=context,proto3" json:"context,omitempty"`
	FileInfoDiff *entities.FileInfoDiff `protobuf:"bytes,14,opt,name=file_info_diff,json=fileInfoDiff,proto3" json:"file_info_diff,omitempty"`
	LineType     CommentLineType        `protobuf:"varint,15,opt,name=line_type,json=lineType,proto3,enum=codehost.CommentLineType" json:"line_type,omitempty"`
	// Original information
	OriginalLocation     *ReviewCommentLocation    `protobuf:"bytes,16,opt,name=original_location,json=originalLocation,proto3" json:"original_location,omitempty"`
	ExternalId           string                    `protobuf:"bytes,17,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	ExternalNodeId       string                    `protobuf:"bytes,18,opt,name=external_node_id,json=externalNodeId,proto3" json:"external_node_id,omitempty"`
	ExternalReplyTo      string                    `protobuf:"bytes,19,opt,name=external_reply_to,json=externalReplyTo,proto3" json:"external_reply_to,omitempty"`
	ExternalReplyToNode  string                    `protobuf:"bytes,20,opt,name=external_reply_to_node,json=externalReplyToNode,proto3" json:"external_reply_to_node,omitempty"`
	ExternalDiscussionId string                    `protobuf:"bytes,21,opt,name=external_discussion_id,json=externalDiscussionId,proto3" json:"external_discussion_id,omitempty"`
	ExternalCreatedAt    int64                     `protobuf:"varint,22,opt,name=external_created_at,json=externalCreatedAt,proto3" json:"external_created_at,omitempty"`
	ExternalUpdatedAt    int64                     `protobuf:"varint,23,opt,name=external_updated_at,json=externalUpdatedAt,proto3" json:"external_updated_at,omitempty"`
	ExternalReviewId     string                    `protobuf:"bytes,24,opt,name=external_review_id,json=externalReviewId,proto3" json:"external_review_id,omitempty"`
	CreatedAt            int64                     `protobuf:"varint,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64                     `protobuf:"varint,26,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Diff                 *entities.StaticFileDiffs `protobuf:"bytes,27,opt,name=diff,proto3" json:"diff,omitempty"`
	RelatedCommentsId    []string                  `protobuf:"bytes,28,rep,name=related_comments_id,json=relatedCommentsId,proto3" json:"related_comments_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReviewComment) Reset() {
	*x = ReviewComment{}
	mi := &file_codehost_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewComment) ProtoMessage() {}

func (x *ReviewComment) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewComment.ProtoReflect.Descriptor instead.
func (*ReviewComment) Descriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewComment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReviewComment) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *ReviewComment) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *ReviewComment) GetSeverity() CommentSeverity {
	if x != nil {
		return x.Severity
	}
	return CommentSeverity_LOW
}

func (x *ReviewComment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ReviewComment) GetCodeReviewId() string {
	if x != nil {
		return x.CodeReviewId
	}
	return ""
}

func (x *ReviewComment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReviewComment) GetUserReviewId() string {
	if x != nil {
		return x.UserReviewId
	}
	return ""
}

func (x *ReviewComment) GetLocation() *ReviewCommentLocation {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ReviewComment) GetResolved() bool {
	if x != nil && x.Resolved != nil {
		return *x.Resolved
	}
	return false
}

func (x *ReviewComment) GetType() CommentType {
	if x != nil {
		return x.Type
	}
	return CommentType_UNKNOWN
}

func (x *ReviewComment) GetIsOutdated() bool {
	if x != nil {
		return x.IsOutdated
	}
	return false
}

func (x *ReviewComment) GetContext() *entities.ChangesBlock {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReviewComment) GetFileInfoDiff() *entities.FileInfoDiff {
	if x != nil {
		return x.FileInfoDiff
	}
	return nil
}

func (x *ReviewComment) GetLineType() CommentLineType {
	if x != nil {
		return x.LineType
	}
	return CommentLineType_LINE_ADDED
}

func (x *ReviewComment) GetOriginalLocation() *ReviewCommentLocation {
	if x != nil {
		return x.OriginalLocation
	}
	return nil
}

func (x *ReviewComment) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *ReviewComment) GetExternalNodeId() string {
	if x != nil {
		return x.ExternalNodeId
	}
	return ""
}

func (x *ReviewComment) GetExternalReplyTo() string {
	if x != nil {
		return x.ExternalReplyTo
	}
	return ""
}

func (x *ReviewComment) GetExternalReplyToNode() string {
	if x != nil {
		return x.ExternalReplyToNode
	}
	return ""
}

func (x *ReviewComment) GetExternalDiscussionId() string {
	if x != nil {
		return x.ExternalDiscussionId
	}
	return ""
}

func (x *ReviewComment) GetExternalCreatedAt() int64 {
	if x != nil {
		return x.ExternalCreatedAt
	}
	return 0
}

func (x *ReviewComment) GetExternalUpdatedAt() int64 {
	if x != nil {
		return x.ExternalUpdatedAt
	}
	return 0
}

func (x *ReviewComment) GetExternalReviewId() string {
	if x != nil {
		return x.ExternalReviewId
	}
	return ""
}

func (x *ReviewComment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ReviewComment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *ReviewComment) GetDiff() *entities.StaticFileDiffs {
	if x != nil {
		return x.Diff
	}
	return nil
}

func (x *ReviewComment) GetRelatedCommentsId() []string {
	if x != nil {
		return x.RelatedCommentsId
	}
	return nil
}

type ReviewCommentLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewPath       string                 `protobuf:"bytes,1,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	OldPath       string                 `protobuf:"bytes,2,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	BaseCommitId  string                 `protobuf:"bytes,3,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	HeadCommitId  string                 `protobuf:"bytes,4,opt,name=head_commit_id,json=headCommitId,proto3" json:"head_commit_id,omitempty"`
	NewLine       int32                  `protobuf:"varint,5,opt,name=new_line,json=newLine,proto3" json:"new_line,omitempty"`
	OldLine       int32                  `protobuf:"varint,6,opt,name=old_line,json=oldLine,proto3" json:"old_line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewCommentLocation) Reset() {
	*x = ReviewCommentLocation{}
	mi := &file_codehost_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewCommentLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewCommentLocation) ProtoMessage() {}

func (x *ReviewCommentLocation) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewCommentLocation.ProtoReflect.Descriptor instead.
func (*ReviewCommentLocation) Descriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewCommentLocation) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

func (x *ReviewCommentLocation) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *ReviewCommentLocation) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *ReviewCommentLocation) GetHeadCommitId() string {
	if x != nil {
		return x.HeadCommitId
	}
	return ""
}

func (x *ReviewCommentLocation) GetNewLine() int32 {
	if x != nil {
		return x.NewLine
	}
	return 0
}

func (x *ReviewCommentLocation) GetOldLine() int32 {
	if x != nil {
		return x.OldLine
	}
	return 0
}

type ReviewFileComments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*ReviewComment       `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewFileComments) Reset() {
	*x = ReviewFileComments{}
	mi := &file_codehost_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewFileComments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewFileComments) ProtoMessage() {}

func (x *ReviewFileComments) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewFileComments.ProtoReflect.Descriptor instead.
func (*ReviewFileComments) Descriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{2}
}

func (x *ReviewFileComments) GetComments() []*ReviewComment {
	if x != nil {
		return x.Comments
	}
	return nil
}

type ReviewDiscussionCountBySeverity struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	BySeverity    map[string]*ReviewDiscussionCount `protobuf:"bytes,1,rep,name=by_severity,json=bySeverity,proto3" json:"by_severity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewDiscussionCountBySeverity) Reset() {
	*x = ReviewDiscussionCountBySeverity{}
	mi := &file_codehost_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewDiscussionCountBySeverity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewDiscussionCountBySeverity) ProtoMessage() {}

func (x *ReviewDiscussionCountBySeverity) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewDiscussionCountBySeverity.ProtoReflect.Descriptor instead.
func (*ReviewDiscussionCountBySeverity) Descriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{3}
}

func (x *ReviewDiscussionCountBySeverity) GetBySeverity() map[string]*ReviewDiscussionCount {
	if x != nil {
		return x.BySeverity
	}
	return nil
}

type ReviewDiscussionCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Resolved      int32                  `protobuf:"varint,2,opt,name=resolved,proto3" json:"resolved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewDiscussionCount) Reset() {
	*x = ReviewDiscussionCount{}
	mi := &file_codehost_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewDiscussionCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewDiscussionCount) ProtoMessage() {}

func (x *ReviewDiscussionCount) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewDiscussionCount.ProtoReflect.Descriptor instead.
func (*ReviewDiscussionCount) Descriptor() ([]byte, []int) {
	return file_codehost_comment_proto_rawDescGZIP(), []int{4}
}

func (x *ReviewDiscussionCount) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ReviewDiscussionCount) GetResolved() int32 {
	if x != nil {
		return x.Resolved
	}
	return 0
}

var File_codehost_comment_proto protoreflect.FileDescriptor

const file_codehost_comment_proto_rawDesc = "" +
	"\n" +
	"\x16codehost/comment.proto\x12\bcodehost\x1a\x13codehost/user.proto\x1a\x13entities/file.proto\x1a\x17entities/git_diff.proto\x1a\x1centities/semantic_diff.proto\"\xcc\t\n" +
	"\rReviewComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\breply_to\x18\x02 \x01(\tR\areplyTo\x12&\n" +
	"\x06author\x18\x03 \x01(\v2\x0e.codehost.UserR\x06author\x125\n" +
	"\bseverity\x18\x04 \x01(\x0e2\x19.codehost.CommentSeverityR\bseverity\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12$\n" +
	"\x0ecode_review_id\x18\x06 \x01(\tR\fcodeReviewId\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x12$\n" +
	"\x0euser_review_id\x18\b \x01(\tR\fuserReviewId\x12;\n" +
	"\blocation\x18\t \x01(\v2\x1f.codehost.ReviewCommentLocationR\blocation\x12\x1f\n" +
	"\bresolved\x18\n" +
	" \x01(\bH\x00R\bresolved\x88\x01\x01\x12)\n" +
	"\x04type\x18\v \x01(\x0e2\x15.codehost.CommentTypeR\x04type\x12\x1f\n" +
	"\vis_outdated\x18\f \x01(\bR\n" +
	"isOutdated\x120\n" +
	"\acontext\x18\r \x01(\v2\x16.entities.ChangesBlockR\acontext\x12<\n" +
	"\x0efile_info_diff\x18\x0e \x01(\v2\x16.entities.FileInfoDiffR\ffileInfoDiff\x126\n" +
	"\tline_type\x18\x0f \x01(\x0e2\x19.codehost.CommentLineTypeR\blineType\x12L\n" +
	"\x11original_location\x18\x10 \x01(\v2\x1f.codehost.ReviewCommentLocationR\x10originalLocation\x12\x1f\n" +
	"\vexternal_id\x18\x11 \x01(\tR\n" +
	"externalId\x12(\n" +
	"\x10external_node_id\x18\x12 \x01(\tR\x0eexternalNodeId\x12*\n" +
	"\x11external_reply_to\x18\x13 \x01(\tR\x0fexternalReplyTo\x123\n" +
	"\x16external_reply_to_node\x18\x14 \x01(\tR\x13externalReplyToNode\x124\n" +
	"\x16external_discussion_id\x18\x15 \x01(\tR\x14externalDiscussionId\x12.\n" +
	"\x13external_created_at\x18\x16 \x01(\x03R\x11externalCreatedAt\x12.\n" +
	"\x13external_updated_at\x18\x17 \x01(\x03R\x11externalUpdatedAt\x12,\n" +
	"\x12external_review_id\x18\x18 \x01(\tR\x10externalReviewId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x19 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x1a \x01(\x03R\tupdatedAt\x12-\n" +
	"\x04diff\x18\x1b \x01(\v2\x19.entities.StaticFileDiffsR\x04diff\x12.\n" +
	"\x13related_comments_id\x18\x1c \x03(\tR\x11relatedCommentsIdB\v\n" +
	"\t_resolved\"\xcf\x01\n" +
	"\x15ReviewCommentLocation\x12\x19\n" +
	"\bnew_path\x18\x01 \x01(\tR\anewPath\x12\x19\n" +
	"\bold_path\x18\x02 \x01(\tR\aoldPath\x12$\n" +
	"\x0ebase_commit_id\x18\x03 \x01(\tR\fbaseCommitId\x12$\n" +
	"\x0ehead_commit_id\x18\x04 \x01(\tR\fheadCommitId\x12\x19\n" +
	"\bnew_line\x18\x05 \x01(\x05R\anewLine\x12\x19\n" +
	"\bold_line\x18\x06 \x01(\x05R\aoldLine\"I\n" +
	"\x12ReviewFileComments\x123\n" +
	"\bcomments\x18\x01 \x03(\v2\x17.codehost.ReviewCommentR\bcomments\"\xdd\x01\n" +
	"\x1fReviewDiscussionCountBySeverity\x12Z\n" +
	"\vby_severity\x18\x01 \x03(\v29.codehost.ReviewDiscussionCountBySeverity.BySeverityEntryR\n" +
	"bySeverity\x1a^\n" +
	"\x0fBySeverityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.codehost.ReviewDiscussionCountR\x05value:\x028\x01\"I\n" +
	"\x15ReviewDiscussionCount\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x1a\n" +
	"\bresolved\x18\x02 \x01(\x05R\bresolved*0\n" +
	"\x0fCommentSeverity\x12\a\n" +
	"\x03LOW\x10\x00\x12\n" +
	"\n" +
	"\x06MEDIUM\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02*1\n" +
	"\vCommentType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04DIFF\x10\x01\x12\v\n" +
	"\aGENERAL\x10\x02*E\n" +
	"\x0fCommentLineType\x12\x0e\n" +
	"\n" +
	"LINE_ADDED\x10\x00\x12\x10\n" +
	"\fLINE_REMOVED\x10\x01\x12\x10\n" +
	"\fCONTEXT_LINE\x10\x02B&Z$github.com/reviewpad/api/go/codehostb\x06proto3"

var (
	file_codehost_comment_proto_rawDescOnce sync.Once
	file_codehost_comment_proto_rawDescData []byte
)

func file_codehost_comment_proto_rawDescGZIP() []byte {
	file_codehost_comment_proto_rawDescOnce.Do(func() {
		file_codehost_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codehost_comment_proto_rawDesc), len(file_codehost_comment_proto_rawDesc)))
	})
	return file_codehost_comment_proto_rawDescData
}

var file_codehost_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_codehost_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_codehost_comment_proto_goTypes = []any{
	(CommentSeverity)(0),                    // 0: codehost.CommentSeverity
	(CommentType)(0),                        // 1: codehost.CommentType
	(CommentLineType)(0),                    // 2: codehost.CommentLineType
	(*ReviewComment)(nil),                   // 3: codehost.ReviewComment
	(*ReviewCommentLocation)(nil),           // 4: codehost.ReviewCommentLocation
	(*ReviewFileComments)(nil),              // 5: codehost.ReviewFileComments
	(*ReviewDiscussionCountBySeverity)(nil), // 6: codehost.ReviewDiscussionCountBySeverity
	(*ReviewDiscussionCount)(nil),           // 7: codehost.ReviewDiscussionCount
	nil,                                     // 8: codehost.ReviewDiscussionCountBySeverity.BySeverityEntry
	(*User)(nil),                            // 9: codehost.User
	(*entities.ChangesBlock)(nil),           // 10: entities.ChangesBlock
	(*entities.FileInfoDiff)(nil),           // 11: entities.FileInfoDiff
	(*entities.StaticFileDiffs)(nil),        // 12: entities.StaticFileDiffs
}
var file_codehost_comment_proto_depIdxs = []int32{
	9,  // 0: codehost.ReviewComment.author:type_name -> codehost.User
	0,  // 1: codehost.ReviewComment.severity:type_name -> codehost.CommentSeverity
	4,  // 2: codehost.ReviewComment.location:type_name -> codehost.ReviewCommentLocation
	1,  // 3: codehost.ReviewComment.type:type_name -> codehost.CommentType
	10, // 4: codehost.ReviewComment.context:type_name -> entities.ChangesBlock
	11, // 5: codehost.ReviewComment.file_info_diff:type_name -> entities.FileInfoDiff
	2,  // 6: codehost.ReviewComment.line_type:type_name -> codehost.CommentLineType
	4,  // 7: codehost.ReviewComment.original_location:type_name -> codehost.ReviewCommentLocation
	12, // 8: codehost.ReviewComment.diff:type_name -> entities.StaticFileDiffs
	3,  // 9: codehost.ReviewFileComments.comments:type_name -> codehost.ReviewComment
	8,  // 10: codehost.ReviewDiscussionCountBySeverity.by_severity:type_name -> codehost.ReviewDiscussionCountBySeverity.BySeverityEntry
	7,  // 11: codehost.ReviewDiscussionCountBySeverity.BySeverityEntry.value:type_name -> codehost.ReviewDiscussionCount
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_codehost_comment_proto_init() }
func file_codehost_comment_proto_init() {
	if File_codehost_comment_proto != nil {
		return
	}
	file_codehost_user_proto_init()
	file_codehost_comment_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codehost_comment_proto_rawDesc), len(file_codehost_comment_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codehost_comment_proto_goTypes,
		DependencyIndexes: file_codehost_comment_proto_depIdxs,
		EnumInfos:         file_codehost_comment_proto_enumTypes,
		MessageInfos:      file_codehost_comment_proto_msgTypes,
	}.Build()
	File_codehost_comment_proto = out.File
	file_codehost_comment_proto_goTypes = nil
	file_codehost_comment_proto_depIdxs = nil
}
