// Copyright (C) 2023 Explore.dev, Unipessoal Lda - All Rights Reserved
// Unauthorized copying of this file, via any medium is strictly prohibited
// Proprietary and confidential

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: codehost/merge.proto

package codehost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MergeMethod int32

const (
	MergeMethod_MERGE                    MergeMethod = 0 // Creates merge commit; blocks operation if there are conflicts
	MergeMethod_REBASE                   MergeMethod = 1 // Tries to rebase source branch into target branch; blocks operation if there are (intermediate) conflicts
	MergeMethod_SQUASH                   MergeMethod = 2 // Creates single squash commit; blocks operation if there are conflicts
	MergeMethod_FAST_FORWARD             MergeMethod = 3 // Tries to fast-forward target branch to source branch; creates merge commit otherwise if there are no conflicts
	MergeMethod_FAST_FORWARD_ONLY        MergeMethod = 4 // Tries to fast-forward target branch to source branch if up-to-date; blocks operation if outdated
	MergeMethod_REBASE_AND_MERGE         MergeMethod = 5 // Same as REBASE but with a merge commit in the end
	MergeMethod_SQUASH_FAST_FORWARD_ONLY MergeMethod = 6 // Same as SQUASH, except operation is blocked if source branch is outdated
)

// Enum value maps for MergeMethod.
var (
	MergeMethod_name = map[int32]string{
		0: "MERGE",
		1: "REBASE",
		2: "SQUASH",
		3: "FAST_FORWARD",
		4: "FAST_FORWARD_ONLY",
		5: "REBASE_AND_MERGE",
		6: "SQUASH_FAST_FORWARD_ONLY",
	}
	MergeMethod_value = map[string]int32{
		"MERGE":                    0,
		"REBASE":                   1,
		"SQUASH":                   2,
		"FAST_FORWARD":             3,
		"FAST_FORWARD_ONLY":        4,
		"REBASE_AND_MERGE":         5,
		"SQUASH_FAST_FORWARD_ONLY": 6,
	}
)

func (x MergeMethod) Enum() *MergeMethod {
	p := new(MergeMethod)
	*p = x
	return p
}

func (x MergeMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MergeMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_merge_proto_enumTypes[0].Descriptor()
}

func (MergeMethod) Type() protoreflect.EnumType {
	return &file_codehost_merge_proto_enumTypes[0]
}

func (x MergeMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MergeMethod.Descriptor instead.
func (MergeMethod) EnumDescriptor() ([]byte, []int) {
	return file_codehost_merge_proto_rawDescGZIP(), []int{0}
}

type DeleteHeadOption int32

const (
	DeleteHeadOption_PRESERVE DeleteHeadOption = 0
	DeleteHeadOption_DELETE   DeleteHeadOption = 1
)

// Enum value maps for DeleteHeadOption.
var (
	DeleteHeadOption_name = map[int32]string{
		0: "PRESERVE",
		1: "DELETE",
	}
	DeleteHeadOption_value = map[string]int32{
		"PRESERVE": 0,
		"DELETE":   1,
	}
)

func (x DeleteHeadOption) Enum() *DeleteHeadOption {
	p := new(DeleteHeadOption)
	*p = x
	return p
}

func (x DeleteHeadOption) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeleteHeadOption) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_merge_proto_enumTypes[1].Descriptor()
}

func (DeleteHeadOption) Type() protoreflect.EnumType {
	return &file_codehost_merge_proto_enumTypes[1]
}

func (x DeleteHeadOption) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeleteHeadOption.Descriptor instead.
func (DeleteHeadOption) EnumDescriptor() ([]byte, []int) {
	return file_codehost_merge_proto_rawDescGZIP(), []int{1}
}

type MergeMethodOptions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MergeMethod     MergeMethod            `protobuf:"varint,1,opt,name=merge_method,json=mergeMethod,proto3,enum=codehost.MergeMethod" json:"merge_method,omitempty"`
	RequiresMessage bool                   `protobuf:"varint,2,opt,name=requires_message,json=requiresMessage,proto3" json:"requires_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MergeMethodOptions) Reset() {
	*x = MergeMethodOptions{}
	mi := &file_codehost_merge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MergeMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MergeMethodOptions) ProtoMessage() {}

func (x *MergeMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_merge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MergeMethodOptions.ProtoReflect.Descriptor instead.
func (*MergeMethodOptions) Descriptor() ([]byte, []int) {
	return file_codehost_merge_proto_rawDescGZIP(), []int{0}
}

func (x *MergeMethodOptions) GetMergeMethod() MergeMethod {
	if x != nil {
		return x.MergeMethod
	}
	return MergeMethod_MERGE
}

func (x *MergeMethodOptions) GetRequiresMessage() bool {
	if x != nil {
		return x.RequiresMessage
	}
	return false
}

var File_codehost_merge_proto protoreflect.FileDescriptor

const file_codehost_merge_proto_rawDesc = "" +
	"\n" +
	"\x14codehost/merge.proto\x12\bcodehost\"y\n" +
	"\x12MergeMethodOptions\x128\n" +
	"\fmerge_method\x18\x01 \x01(\x0e2\x15.codehost.MergeMethodR\vmergeMethod\x12)\n" +
	"\x10requires_message\x18\x02 \x01(\bR\x0frequiresMessage*\x8d\x01\n" +
	"\vMergeMethod\x12\t\n" +
	"\x05MERGE\x10\x00\x12\n" +
	"\n" +
	"\x06REBASE\x10\x01\x12\n" +
	"\n" +
	"\x06SQUASH\x10\x02\x12\x10\n" +
	"\fFAST_FORWARD\x10\x03\x12\x15\n" +
	"\x11FAST_FORWARD_ONLY\x10\x04\x12\x14\n" +
	"\x10REBASE_AND_MERGE\x10\x05\x12\x1c\n" +
	"\x18SQUASH_FAST_FORWARD_ONLY\x10\x06*,\n" +
	"\x10DeleteHeadOption\x12\f\n" +
	"\bPRESERVE\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01B&Z$github.com/reviewpad/api/go/codehostb\x06proto3"

var (
	file_codehost_merge_proto_rawDescOnce sync.Once
	file_codehost_merge_proto_rawDescData []byte
)

func file_codehost_merge_proto_rawDescGZIP() []byte {
	file_codehost_merge_proto_rawDescOnce.Do(func() {
		file_codehost_merge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codehost_merge_proto_rawDesc), len(file_codehost_merge_proto_rawDesc)))
	})
	return file_codehost_merge_proto_rawDescData
}

var file_codehost_merge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_codehost_merge_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_codehost_merge_proto_goTypes = []any{
	(MergeMethod)(0),           // 0: codehost.MergeMethod
	(DeleteHeadOption)(0),      // 1: codehost.DeleteHeadOption
	(*MergeMethodOptions)(nil), // 2: codehost.MergeMethodOptions
}
var file_codehost_merge_proto_depIdxs = []int32{
	0, // 0: codehost.MergeMethodOptions.merge_method:type_name -> codehost.MergeMethod
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_codehost_merge_proto_init() }
func file_codehost_merge_proto_init() {
	if File_codehost_merge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codehost_merge_proto_rawDesc), len(file_codehost_merge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codehost_merge_proto_goTypes,
		DependencyIndexes: file_codehost_merge_proto_depIdxs,
		EnumInfos:         file_codehost_merge_proto_enumTypes,
		MessageInfos:      file_codehost_merge_proto_msgTypes,
	}.Build()
	File_codehost_merge_proto = out.File
	file_codehost_merge_proto_goTypes = nil
	file_codehost_merge_proto_depIdxs = nil
}
