// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: codehost/pull_request.proto

package codehost

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PullRequestStatus int32

const (
	PullRequestStatus_OPEN   PullRequestStatus = 0
	PullRequestStatus_CLOSED PullRequestStatus = 1
	PullRequestStatus_MERGED PullRequestStatus = 2
	PullRequestStatus_LOCKED PullRequestStatus = 3
)

// Enum value maps for PullRequestStatus.
var (
	PullRequestStatus_name = map[int32]string{
		0: "OPEN",
		1: "CLOSED",
		2: "MERGED",
		3: "LOCKED",
	}
	PullRequestStatus_value = map[string]int32{
		"OPEN":   0,
		"CLOSED": 1,
		"MERGED": 2,
		"LOCKED": 3,
	}
)

func (x PullRequestStatus) Enum() *PullRequestStatus {
	p := new(PullRequestStatus)
	*p = x
	return p
}

func (x PullRequestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PullRequestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_codehost_pull_request_proto_enumTypes[0].Descriptor()
}

func (PullRequestStatus) Type() protoreflect.EnumType {
	return &file_codehost_pull_request_proto_enumTypes[0]
}

func (x PullRequestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PullRequestStatus.Descriptor instead.
func (PullRequestStatus) EnumDescriptor() ([]byte, []int) {
	return file_codehost_pull_request_proto_rawDescGZIP(), []int{0}
}

type PullRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the code review. usually the id of the object we get for the GraphQL API
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Number             int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status             PullRequestStatus      `protobuf:"varint,5,opt,name=status,proto3,enum=codehost.PullRequestStatus" json:"status,omitempty"`
	IsDraft            bool                   `protobuf:"varint,6,opt,name=is_draft,json=isDraft,proto3" json:"is_draft,omitempty"`
	IsMerged           bool                   `protobuf:"varint,7,opt,name=is_merged,json=isMerged,proto3" json:"is_merged,omitempty"`
	IsClosed           bool                   `protobuf:"varint,8,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	IsRebaseable       bool                   `protobuf:"varint,9,opt,name=is_rebaseable,json=isRebaseable,proto3" json:"is_rebaseable,omitempty"`
	CommentsCount      int64                  `protobuf:"varint,10,opt,name=comments_count,json=commentsCount,proto3" json:"comments_count,omitempty"`
	CommitsCount       int64                  `protobuf:"varint,11,opt,name=commits_count,json=commitsCount,proto3" json:"commits_count,omitempty"`
	AdditionsCount     int64                  `protobuf:"varint,12,opt,name=additions_count,json=additionsCount,proto3" json:"additions_count,omitempty"`
	DeletionsCount     int64                  `protobuf:"varint,13,opt,name=deletions_count,json=deletionsCount,proto3" json:"deletions_count,omitempty"`
	ChangedFilesCount  int64                  `protobuf:"varint,14,opt,name=changed_files_count,json=changedFilesCount,proto3" json:"changed_files_count,omitempty"`
	Url                string                 `protobuf:"bytes,15,opt,name=url,proto3" json:"url,omitempty"`
	ClosedAt           *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	MergedAt           *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=merged_at,json=mergedAt,proto3" json:"merged_at,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Base               *Branch                `protobuf:"bytes,20,opt,name=base,proto3" json:"base,omitempty"`
	Head               *Branch                `protobuf:"bytes,21,opt,name=head,proto3" json:"head,omitempty"`
	Author             *User                  `protobuf:"bytes,22,opt,name=author,proto3" json:"author,omitempty"`
	Assignees          []*User                `protobuf:"bytes,23,rep,name=assignees,proto3" json:"assignees,omitempty"`
	Labels             []*Label               `protobuf:"bytes,24,rep,name=labels,proto3" json:"labels,omitempty"`
	Milestone          *Milestone             `protobuf:"bytes,25,opt,name=milestone,proto3" json:"milestone,omitempty"`
	RequestedReviewers *RequestedReviewers    `protobuf:"bytes,26,opt,name=requested_reviewers,json=requestedReviewers,proto3" json:"requested_reviewers,omitempty"`
	// A JSON encoded presentation of the raw pull request / merge request object
	// usually the response we get from the REST API of the provider
	RawRestResponse string `protobuf:"bytes,27,opt,name=raw_rest_response,json=rawRestResponse,proto3" json:"raw_rest_response,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	mi := &file_codehost_pull_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_pull_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_codehost_pull_request_proto_rawDescGZIP(), []int{0}
}

func (x *PullRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PullRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PullRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PullRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PullRequest) GetStatus() PullRequestStatus {
	if x != nil {
		return x.Status
	}
	return PullRequestStatus_OPEN
}

func (x *PullRequest) GetIsDraft() bool {
	if x != nil {
		return x.IsDraft
	}
	return false
}

func (x *PullRequest) GetIsMerged() bool {
	if x != nil {
		return x.IsMerged
	}
	return false
}

func (x *PullRequest) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

func (x *PullRequest) GetIsRebaseable() bool {
	if x != nil {
		return x.IsRebaseable
	}
	return false
}

func (x *PullRequest) GetCommentsCount() int64 {
	if x != nil {
		return x.CommentsCount
	}
	return 0
}

func (x *PullRequest) GetCommitsCount() int64 {
	if x != nil {
		return x.CommitsCount
	}
	return 0
}

func (x *PullRequest) GetAdditionsCount() int64 {
	if x != nil {
		return x.AdditionsCount
	}
	return 0
}

func (x *PullRequest) GetDeletionsCount() int64 {
	if x != nil {
		return x.DeletionsCount
	}
	return 0
}

func (x *PullRequest) GetChangedFilesCount() int64 {
	if x != nil {
		return x.ChangedFilesCount
	}
	return 0
}

func (x *PullRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PullRequest) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *PullRequest) GetMergedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.MergedAt
	}
	return nil
}

func (x *PullRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PullRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *PullRequest) GetBase() *Branch {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *PullRequest) GetHead() *Branch {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *PullRequest) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *PullRequest) GetAssignees() []*User {
	if x != nil {
		return x.Assignees
	}
	return nil
}

func (x *PullRequest) GetLabels() []*Label {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PullRequest) GetMilestone() *Milestone {
	if x != nil {
		return x.Milestone
	}
	return nil
}

func (x *PullRequest) GetRequestedReviewers() *RequestedReviewers {
	if x != nil {
		return x.RequestedReviewers
	}
	return nil
}

func (x *PullRequest) GetRawRestResponse() string {
	if x != nil {
		return x.RawRestResponse
	}
	return ""
}

type RequestedReviewers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Teams         []*Team                `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestedReviewers) Reset() {
	*x = RequestedReviewers{}
	mi := &file_codehost_pull_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestedReviewers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestedReviewers) ProtoMessage() {}

func (x *RequestedReviewers) ProtoReflect() protoreflect.Message {
	mi := &file_codehost_pull_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestedReviewers.ProtoReflect.Descriptor instead.
func (*RequestedReviewers) Descriptor() ([]byte, []int) {
	return file_codehost_pull_request_proto_rawDescGZIP(), []int{1}
}

func (x *RequestedReviewers) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *RequestedReviewers) GetTeams() []*Team {
	if x != nil {
		return x.Teams
	}
	return nil
}

var File_codehost_pull_request_proto protoreflect.FileDescriptor

const file_codehost_pull_request_proto_rawDesc = "" +
	"\n" +
	"\x1bcodehost/pull_request.proto\x12\bcodehost\x1a\x13codehost/user.proto\x1a\x14codehost/label.proto\x1a\x13codehost/team.proto\x1a\x18codehost/milestone.proto\x1a\x15codehost/branch.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdd\b\n" +
	"\vPullRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x123\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1b.codehost.PullRequestStatusR\x06status\x12\x19\n" +
	"\bis_draft\x18\x06 \x01(\bR\aisDraft\x12\x1b\n" +
	"\tis_merged\x18\a \x01(\bR\bisMerged\x12\x1b\n" +
	"\tis_closed\x18\b \x01(\bR\bisClosed\x12#\n" +
	"\ris_rebaseable\x18\t \x01(\bR\fisRebaseable\x12%\n" +
	"\x0ecomments_count\x18\n" +
	" \x01(\x03R\rcommentsCount\x12#\n" +
	"\rcommits_count\x18\v \x01(\x03R\fcommitsCount\x12'\n" +
	"\x0fadditions_count\x18\f \x01(\x03R\x0eadditionsCount\x12'\n" +
	"\x0fdeletions_count\x18\r \x01(\x03R\x0edeletionsCount\x12.\n" +
	"\x13changed_files_count\x18\x0e \x01(\x03R\x11changedFilesCount\x12\x10\n" +
	"\x03url\x18\x0f \x01(\tR\x03url\x127\n" +
	"\tclosed_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x127\n" +
	"\tmerged_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\bmergedAt\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\x04base\x18\x14 \x01(\v2\x10.codehost.BranchR\x04base\x12$\n" +
	"\x04head\x18\x15 \x01(\v2\x10.codehost.BranchR\x04head\x12&\n" +
	"\x06author\x18\x16 \x01(\v2\x0e.codehost.UserR\x06author\x12,\n" +
	"\tassignees\x18\x17 \x03(\v2\x0e.codehost.UserR\tassignees\x12'\n" +
	"\x06labels\x18\x18 \x03(\v2\x0f.codehost.LabelR\x06labels\x121\n" +
	"\tmilestone\x18\x19 \x01(\v2\x13.codehost.MilestoneR\tmilestone\x12M\n" +
	"\x13requested_reviewers\x18\x1a \x01(\v2\x1c.codehost.RequestedReviewersR\x12requestedReviewers\x12*\n" +
	"\x11raw_rest_response\x18\x1b \x01(\tR\x0frawRestResponse\"`\n" +
	"\x12RequestedReviewers\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.codehost.UserR\x05users\x12$\n" +
	"\x05teams\x18\x02 \x03(\v2\x0e.codehost.TeamR\x05teams*A\n" +
	"\x11PullRequestStatus\x12\b\n" +
	"\x04OPEN\x10\x00\x12\n" +
	"\n" +
	"\x06CLOSED\x10\x01\x12\n" +
	"\n" +
	"\x06MERGED\x10\x02\x12\n" +
	"\n" +
	"\x06LOCKED\x10\x03B&Z$github.com/reviewpad/api/go/codehostb\x06proto3"

var (
	file_codehost_pull_request_proto_rawDescOnce sync.Once
	file_codehost_pull_request_proto_rawDescData []byte
)

func file_codehost_pull_request_proto_rawDescGZIP() []byte {
	file_codehost_pull_request_proto_rawDescOnce.Do(func() {
		file_codehost_pull_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codehost_pull_request_proto_rawDesc), len(file_codehost_pull_request_proto_rawDesc)))
	})
	return file_codehost_pull_request_proto_rawDescData
}

var file_codehost_pull_request_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_codehost_pull_request_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_codehost_pull_request_proto_goTypes = []any{
	(PullRequestStatus)(0),        // 0: codehost.PullRequestStatus
	(*PullRequest)(nil),           // 1: codehost.PullRequest
	(*RequestedReviewers)(nil),    // 2: codehost.RequestedReviewers
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Branch)(nil),                // 4: codehost.Branch
	(*User)(nil),                  // 5: codehost.User
	(*Label)(nil),                 // 6: codehost.Label
	(*Milestone)(nil),             // 7: codehost.Milestone
	(*Team)(nil),                  // 8: codehost.Team
}
var file_codehost_pull_request_proto_depIdxs = []int32{
	0,  // 0: codehost.PullRequest.status:type_name -> codehost.PullRequestStatus
	3,  // 1: codehost.PullRequest.closed_at:type_name -> google.protobuf.Timestamp
	3,  // 2: codehost.PullRequest.merged_at:type_name -> google.protobuf.Timestamp
	3,  // 3: codehost.PullRequest.created_at:type_name -> google.protobuf.Timestamp
	3,  // 4: codehost.PullRequest.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: codehost.PullRequest.base:type_name -> codehost.Branch
	4,  // 6: codehost.PullRequest.head:type_name -> codehost.Branch
	5,  // 7: codehost.PullRequest.author:type_name -> codehost.User
	5,  // 8: codehost.PullRequest.assignees:type_name -> codehost.User
	6,  // 9: codehost.PullRequest.labels:type_name -> codehost.Label
	7,  // 10: codehost.PullRequest.milestone:type_name -> codehost.Milestone
	2,  // 11: codehost.PullRequest.requested_reviewers:type_name -> codehost.RequestedReviewers
	5,  // 12: codehost.RequestedReviewers.users:type_name -> codehost.User
	8,  // 13: codehost.RequestedReviewers.teams:type_name -> codehost.Team
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_codehost_pull_request_proto_init() }
func file_codehost_pull_request_proto_init() {
	if File_codehost_pull_request_proto != nil {
		return
	}
	file_codehost_user_proto_init()
	file_codehost_label_proto_init()
	file_codehost_team_proto_init()
	file_codehost_milestone_proto_init()
	file_codehost_branch_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codehost_pull_request_proto_rawDesc), len(file_codehost_pull_request_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codehost_pull_request_proto_goTypes,
		DependencyIndexes: file_codehost_pull_request_proto_depIdxs,
		EnumInfos:         file_codehost_pull_request_proto_enumTypes,
		MessageInfos:      file_codehost_pull_request_proto_msgTypes,
	}.Build()
	File_codehost_pull_request_proto = out.File
	file_codehost_pull_request_proto_goTypes = nil
	file_codehost_pull_request_proto_depIdxs = nil
}
