// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: entities/code_host.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Host int32

const (
	Host_GITHUB            Host = 0
	Host_GITLAB            Host = 1
	Host_GITHUB_ENTERPRISE Host = 2
	Host_GITLAB_ENTERPRISE Host = 3
	Host_BITBUCKET_SERVER  Host = 4
	Host_BITBUCKET         Host = 5
)

// Enum value maps for Host.
var (
	Host_name = map[int32]string{
		0: "GITHUB",
		1: "GITLAB",
		2: "GITHUB_ENTERPRISE",
		3: "GITLAB_ENTERPRISE",
		4: "BITBUCKET_SERVER",
		5: "BITBUCKET",
	}
	Host_value = map[string]int32{
		"GITHUB":            0,
		"GITLAB":            1,
		"GITHUB_ENTERPRISE": 2,
		"GITLAB_ENTERPRISE": 3,
		"BITBUCKET_SERVER":  4,
		"BITBUCKET":         5,
	}
)

func (x Host) Enum() *Host {
	p := new(Host)
	*p = x
	return p
}

func (x Host) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Host) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_code_host_proto_enumTypes[0].Descriptor()
}

func (Host) Type() protoreflect.EnumType {
	return &file_entities_code_host_proto_enumTypes[0]
}

func (x Host) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Host.Descriptor instead.
func (Host) EnumDescriptor() ([]byte, []int) {
	return file_entities_code_host_proto_rawDescGZIP(), []int{0}
}

var File_entities_code_host_proto protoreflect.FileDescriptor

const file_entities_code_host_proto_rawDesc = "" +
	"\n" +
	"\x18entities/code_host.proto\x12\bentities*q\n" +
	"\x04Host\x12\n" +
	"\n" +
	"\x06GITHUB\x10\x00\x12\n" +
	"\n" +
	"\x06GITLAB\x10\x01\x12\x15\n" +
	"\x11GITHUB_ENTERPRISE\x10\x02\x12\x15\n" +
	"\x11GITLAB_ENTERPRISE\x10\x03\x12\x14\n" +
	"\x10BITBUCKET_SERVER\x10\x04\x12\r\n" +
	"\tBITBUCKET\x10\x05B&Z$github.com/reviewpad/api/go/entitiesb\x06proto3"

var (
	file_entities_code_host_proto_rawDescOnce sync.Once
	file_entities_code_host_proto_rawDescData []byte
)

func file_entities_code_host_proto_rawDescGZIP() []byte {
	file_entities_code_host_proto_rawDescOnce.Do(func() {
		file_entities_code_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_code_host_proto_rawDesc), len(file_entities_code_host_proto_rawDesc)))
	})
	return file_entities_code_host_proto_rawDescData
}

var file_entities_code_host_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entities_code_host_proto_goTypes = []any{
	(Host)(0), // 0: entities.Host
}
var file_entities_code_host_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_entities_code_host_proto_init() }
func file_entities_code_host_proto_init() {
	if File_entities_code_host_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_code_host_proto_rawDesc), len(file_entities_code_host_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_code_host_proto_goTypes,
		DependencyIndexes: file_entities_code_host_proto_depIdxs,
		EnumInfos:         file_entities_code_host_proto_enumTypes,
	}.Build()
	File_entities_code_host_proto = out.File
	file_entities_code_host_proto_goTypes = nil
	file_entities_code_host_proto_depIdxs = nil
}
