// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: entities/file.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileInfoDiff struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OldInfo         *FileInfo              `protobuf:"bytes,1,opt,name=old_info,json=oldInfo,proto3" json:"old_info,omitempty"`
	NewInfo         *FileInfo              `protobuf:"bytes,2,opt,name=new_info,json=newInfo,proto3" json:"new_info,omitempty"`
	NumAddedLines   int32                  `protobuf:"varint,3,opt,name=num_added_lines,json=numAddedLines,proto3" json:"num_added_lines,omitempty"`
	NumRemovedLines int32                  `protobuf:"varint,4,opt,name=num_removed_lines,json=numRemovedLines,proto3" json:"num_removed_lines,omitempty"`
	IsBinary        bool                   `protobuf:"varint,5,opt,name=is_binary,json=isBinary,proto3" json:"is_binary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FileInfoDiff) Reset() {
	*x = FileInfoDiff{}
	mi := &file_entities_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfoDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfoDiff) ProtoMessage() {}

func (x *FileInfoDiff) ProtoReflect() protoreflect.Message {
	mi := &file_entities_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfoDiff.ProtoReflect.Descriptor instead.
func (*FileInfoDiff) Descriptor() ([]byte, []int) {
	return file_entities_file_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfoDiff) GetOldInfo() *FileInfo {
	if x != nil {
		return x.OldInfo
	}
	return nil
}

func (x *FileInfoDiff) GetNewInfo() *FileInfo {
	if x != nil {
		return x.NewInfo
	}
	return nil
}

func (x *FileInfoDiff) GetNumAddedLines() int32 {
	if x != nil {
		return x.NumAddedLines
	}
	return 0
}

func (x *FileInfoDiff) GetNumRemovedLines() int32 {
	if x != nil {
		return x.NumRemovedLines
	}
	return 0
}

func (x *FileInfoDiff) GetIsBinary() bool {
	if x != nil {
		return x.IsBinary
	}
	return false
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Extension     string                 `protobuf:"bytes,2,opt,name=extension,proto3" json:"extension,omitempty"`
	BlobId        string                 `protobuf:"bytes,3,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	NumLines      int32                  `protobuf:"varint,4,opt,name=num_lines,json=numLines,proto3" json:"num_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_entities_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_entities_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_entities_file_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *FileInfo) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *FileInfo) GetNumLines() int32 {
	if x != nil {
		return x.NumLines
	}
	return 0
}

var File_entities_file_proto protoreflect.FileDescriptor

const file_entities_file_proto_rawDesc = "" +
	"\n" +
	"\x13entities/file.proto\x12\bentities\"\xdd\x01\n" +
	"\fFileInfoDiff\x12-\n" +
	"\bold_info\x18\x01 \x01(\v2\x12.entities.FileInfoR\aoldInfo\x12-\n" +
	"\bnew_info\x18\x02 \x01(\v2\x12.entities.FileInfoR\anewInfo\x12&\n" +
	"\x0fnum_added_lines\x18\x03 \x01(\x05R\rnumAddedLines\x12*\n" +
	"\x11num_removed_lines\x18\x04 \x01(\x05R\x0fnumRemovedLines\x12\x1b\n" +
	"\tis_binary\x18\x05 \x01(\bR\bisBinary\"r\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\textension\x18\x02 \x01(\tR\textension\x12\x17\n" +
	"\ablob_id\x18\x03 \x01(\tR\x06blobId\x12\x1b\n" +
	"\tnum_lines\x18\x04 \x01(\x05R\bnumLinesB&Z$github.com/reviewpad/api/go/entitiesb\x06proto3"

var (
	file_entities_file_proto_rawDescOnce sync.Once
	file_entities_file_proto_rawDescData []byte
)

func file_entities_file_proto_rawDescGZIP() []byte {
	file_entities_file_proto_rawDescOnce.Do(func() {
		file_entities_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_file_proto_rawDesc), len(file_entities_file_proto_rawDesc)))
	})
	return file_entities_file_proto_rawDescData
}

var file_entities_file_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_entities_file_proto_goTypes = []any{
	(*FileInfoDiff)(nil), // 0: entities.FileInfoDiff
	(*FileInfo)(nil),     // 1: entities.FileInfo
}
var file_entities_file_proto_depIdxs = []int32{
	1, // 0: entities.FileInfoDiff.old_info:type_name -> entities.FileInfo
	1, // 1: entities.FileInfoDiff.new_info:type_name -> entities.FileInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_entities_file_proto_init() }
func file_entities_file_proto_init() {
	if File_entities_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_file_proto_rawDesc), len(file_entities_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_file_proto_goTypes,
		DependencyIndexes: file_entities_file_proto_depIdxs,
		MessageInfos:      file_entities_file_proto_msgTypes,
	}.Build()
	File_entities_file_proto = out.File
	file_entities_file_proto_goTypes = nil
	file_entities_file_proto_depIdxs = nil
}
