// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: entities/git_diff.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GitDiff struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OldCommitId string                 `protobuf:"bytes,1,opt,name=old_commit_id,json=oldCommitId,proto3" json:"old_commit_id,omitempty"`
	NewCommitId string                 `protobuf:"bytes,2,opt,name=new_commit_id,json=newCommitId,proto3" json:"new_commit_id,omitempty"`
	// Map from all file paths to the respective diff: if a file is renamed, both paths are mapped.
	Files         map[string]*FileInfoDiff `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Diffs         map[string]*GitFileDiffs `protobuf:"bytes,4,rep,name=diffs,proto3" json:"diffs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiff) Reset() {
	*x = GitDiff{}
	mi := &file_entities_git_diff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiff) ProtoMessage() {}

func (x *GitDiff) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiff.ProtoReflect.Descriptor instead.
func (*GitDiff) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{0}
}

func (x *GitDiff) GetOldCommitId() string {
	if x != nil {
		return x.OldCommitId
	}
	return ""
}

func (x *GitDiff) GetNewCommitId() string {
	if x != nil {
		return x.NewCommitId
	}
	return ""
}

func (x *GitDiff) GetFiles() map[string]*FileInfoDiff {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *GitDiff) GetDiffs() map[string]*GitFileDiffs {
	if x != nil {
		return x.Diffs
	}
	return nil
}

type GitFileDiffs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*GitDiffBlock        `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitFileDiffs) Reset() {
	*x = GitFileDiffs{}
	mi := &file_entities_git_diff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitFileDiffs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitFileDiffs) ProtoMessage() {}

func (x *GitFileDiffs) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitFileDiffs.ProtoReflect.Descriptor instead.
func (*GitFileDiffs) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{1}
}

func (x *GitFileDiffs) GetBlocks() []*GitDiffBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type GitDiffBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Old   *GitDiffSpan           `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New   *GitDiffSpan           `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	// True iff block is context about changes, i.e., did not change.
	IsContext     bool `protobuf:"varint,3,opt,name=is_context,json=isContext,proto3" json:"is_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiffBlock) Reset() {
	*x = GitDiffBlock{}
	mi := &file_entities_git_diff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiffBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiffBlock) ProtoMessage() {}

func (x *GitDiffBlock) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiffBlock.ProtoReflect.Descriptor instead.
func (*GitDiffBlock) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{2}
}

func (x *GitDiffBlock) GetOld() *GitDiffSpan {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *GitDiffBlock) GetNew() *GitDiffSpan {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *GitDiffBlock) GetIsContext() bool {
	if x != nil {
		return x.IsContext
	}
	return false
}

type GitDiffSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int32                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitDiffSpan) Reset() {
	*x = GitDiffSpan{}
	mi := &file_entities_git_diff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitDiffSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitDiffSpan) ProtoMessage() {}

func (x *GitDiffSpan) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitDiffSpan.ProtoReflect.Descriptor instead.
func (*GitDiffSpan) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{3}
}

func (x *GitDiffSpan) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *GitDiffSpan) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type StaticDiff struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OldCommitId string                 `protobuf:"bytes,1,opt,name=old_commit_id,json=oldCommitId,proto3" json:"old_commit_id,omitempty"`
	NewCommitId string                 `protobuf:"bytes,2,opt,name=new_commit_id,json=newCommitId,proto3" json:"new_commit_id,omitempty"`
	// Map from all file paths to the respective diff: if a file is renamed, both paths are mapped.
	Files         map[string]*FileInfoDiff    `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Diffs         map[string]*StaticFileDiffs `protobuf:"bytes,4,rep,name=diffs,proto3" json:"diffs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticDiff) Reset() {
	*x = StaticDiff{}
	mi := &file_entities_git_diff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDiff) ProtoMessage() {}

func (x *StaticDiff) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDiff.ProtoReflect.Descriptor instead.
func (*StaticDiff) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{4}
}

func (x *StaticDiff) GetOldCommitId() string {
	if x != nil {
		return x.OldCommitId
	}
	return ""
}

func (x *StaticDiff) GetNewCommitId() string {
	if x != nil {
		return x.NewCommitId
	}
	return ""
}

func (x *StaticDiff) GetFiles() map[string]*FileInfoDiff {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *StaticDiff) GetDiffs() map[string]*StaticFileDiffs {
	if x != nil {
		return x.Diffs
	}
	return nil
}

type StaticFileDiffs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*StaticDiffBlock     `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticFileDiffs) Reset() {
	*x = StaticFileDiffs{}
	mi := &file_entities_git_diff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticFileDiffs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticFileDiffs) ProtoMessage() {}

func (x *StaticFileDiffs) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticFileDiffs.ProtoReflect.Descriptor instead.
func (*StaticFileDiffs) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{5}
}

func (x *StaticFileDiffs) GetBlocks() []*StaticDiffBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type StaticDiffBlock struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Old     *GitDiffSpan           `protobuf:"bytes,1,opt,name=old,proto3" json:"old,omitempty"`
	New     *GitDiffSpan           `protobuf:"bytes,2,opt,name=new,proto3" json:"new,omitempty"`
	OldLine string                 `protobuf:"bytes,3,opt,name=old_line,json=oldLine,proto3" json:"old_line,omitempty"`
	NewLine string                 `protobuf:"bytes,4,opt,name=new_line,json=newLine,proto3" json:"new_line,omitempty"`
	// True iff block is context about changes, i.e., did not change.
	IsContext     bool `protobuf:"varint,5,opt,name=is_context,json=isContext,proto3" json:"is_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaticDiffBlock) Reset() {
	*x = StaticDiffBlock{}
	mi := &file_entities_git_diff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaticDiffBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaticDiffBlock) ProtoMessage() {}

func (x *StaticDiffBlock) ProtoReflect() protoreflect.Message {
	mi := &file_entities_git_diff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaticDiffBlock.ProtoReflect.Descriptor instead.
func (*StaticDiffBlock) Descriptor() ([]byte, []int) {
	return file_entities_git_diff_proto_rawDescGZIP(), []int{6}
}

func (x *StaticDiffBlock) GetOld() *GitDiffSpan {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *StaticDiffBlock) GetNew() *GitDiffSpan {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *StaticDiffBlock) GetOldLine() string {
	if x != nil {
		return x.OldLine
	}
	return ""
}

func (x *StaticDiffBlock) GetNewLine() string {
	if x != nil {
		return x.NewLine
	}
	return ""
}

func (x *StaticDiffBlock) GetIsContext() bool {
	if x != nil {
		return x.IsContext
	}
	return false
}

var File_entities_git_diff_proto protoreflect.FileDescriptor

const file_entities_git_diff_proto_rawDesc = "" +
	"\n" +
	"\x17entities/git_diff.proto\x12\bentities\x1a\x13entities/file.proto\"\xdd\x02\n" +
	"\aGitDiff\x12\"\n" +
	"\rold_commit_id\x18\x01 \x01(\tR\voldCommitId\x12\"\n" +
	"\rnew_commit_id\x18\x02 \x01(\tR\vnewCommitId\x122\n" +
	"\x05files\x18\x03 \x03(\v2\x1c.entities.GitDiff.FilesEntryR\x05files\x122\n" +
	"\x05diffs\x18\x04 \x03(\v2\x1c.entities.GitDiff.DiffsEntryR\x05diffs\x1aP\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.entities.FileInfoDiffR\x05value:\x028\x01\x1aP\n" +
	"\n" +
	"DiffsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.entities.GitFileDiffsR\x05value:\x028\x01\">\n" +
	"\fGitFileDiffs\x12.\n" +
	"\x06blocks\x18\x01 \x03(\v2\x16.entities.GitDiffBlockR\x06blocks\"\x7f\n" +
	"\fGitDiffBlock\x12'\n" +
	"\x03old\x18\x01 \x01(\v2\x15.entities.GitDiffSpanR\x03old\x12'\n" +
	"\x03new\x18\x02 \x01(\v2\x15.entities.GitDiffSpanR\x03new\x12\x1d\n" +
	"\n" +
	"is_context\x18\x03 \x01(\bR\tisContext\"5\n" +
	"\vGitDiffSpan\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x05R\x03end\"\xe9\x02\n" +
	"\n" +
	"StaticDiff\x12\"\n" +
	"\rold_commit_id\x18\x01 \x01(\tR\voldCommitId\x12\"\n" +
	"\rnew_commit_id\x18\x02 \x01(\tR\vnewCommitId\x125\n" +
	"\x05files\x18\x03 \x03(\v2\x1f.entities.StaticDiff.FilesEntryR\x05files\x125\n" +
	"\x05diffs\x18\x04 \x03(\v2\x1f.entities.StaticDiff.DiffsEntryR\x05diffs\x1aP\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.entities.FileInfoDiffR\x05value:\x028\x01\x1aS\n" +
	"\n" +
	"DiffsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.entities.StaticFileDiffsR\x05value:\x028\x01\"D\n" +
	"\x0fStaticFileDiffs\x121\n" +
	"\x06blocks\x18\x01 \x03(\v2\x19.entities.StaticDiffBlockR\x06blocks\"\xb8\x01\n" +
	"\x0fStaticDiffBlock\x12'\n" +
	"\x03old\x18\x01 \x01(\v2\x15.entities.GitDiffSpanR\x03old\x12'\n" +
	"\x03new\x18\x02 \x01(\v2\x15.entities.GitDiffSpanR\x03new\x12\x19\n" +
	"\bold_line\x18\x03 \x01(\tR\aoldLine\x12\x19\n" +
	"\bnew_line\x18\x04 \x01(\tR\anewLine\x12\x1d\n" +
	"\n" +
	"is_context\x18\x05 \x01(\bR\tisContextB&Z$github.com/reviewpad/api/go/entitiesb\x06proto3"

var (
	file_entities_git_diff_proto_rawDescOnce sync.Once
	file_entities_git_diff_proto_rawDescData []byte
)

func file_entities_git_diff_proto_rawDescGZIP() []byte {
	file_entities_git_diff_proto_rawDescOnce.Do(func() {
		file_entities_git_diff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_git_diff_proto_rawDesc), len(file_entities_git_diff_proto_rawDesc)))
	})
	return file_entities_git_diff_proto_rawDescData
}

var file_entities_git_diff_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_entities_git_diff_proto_goTypes = []any{
	(*GitDiff)(nil),         // 0: entities.GitDiff
	(*GitFileDiffs)(nil),    // 1: entities.GitFileDiffs
	(*GitDiffBlock)(nil),    // 2: entities.GitDiffBlock
	(*GitDiffSpan)(nil),     // 3: entities.GitDiffSpan
	(*StaticDiff)(nil),      // 4: entities.StaticDiff
	(*StaticFileDiffs)(nil), // 5: entities.StaticFileDiffs
	(*StaticDiffBlock)(nil), // 6: entities.StaticDiffBlock
	nil,                     // 7: entities.GitDiff.FilesEntry
	nil,                     // 8: entities.GitDiff.DiffsEntry
	nil,                     // 9: entities.StaticDiff.FilesEntry
	nil,                     // 10: entities.StaticDiff.DiffsEntry
	(*FileInfoDiff)(nil),    // 11: entities.FileInfoDiff
}
var file_entities_git_diff_proto_depIdxs = []int32{
	7,  // 0: entities.GitDiff.files:type_name -> entities.GitDiff.FilesEntry
	8,  // 1: entities.GitDiff.diffs:type_name -> entities.GitDiff.DiffsEntry
	2,  // 2: entities.GitFileDiffs.blocks:type_name -> entities.GitDiffBlock
	3,  // 3: entities.GitDiffBlock.old:type_name -> entities.GitDiffSpan
	3,  // 4: entities.GitDiffBlock.new:type_name -> entities.GitDiffSpan
	9,  // 5: entities.StaticDiff.files:type_name -> entities.StaticDiff.FilesEntry
	10, // 6: entities.StaticDiff.diffs:type_name -> entities.StaticDiff.DiffsEntry
	6,  // 7: entities.StaticFileDiffs.blocks:type_name -> entities.StaticDiffBlock
	3,  // 8: entities.StaticDiffBlock.old:type_name -> entities.GitDiffSpan
	3,  // 9: entities.StaticDiffBlock.new:type_name -> entities.GitDiffSpan
	11, // 10: entities.GitDiff.FilesEntry.value:type_name -> entities.FileInfoDiff
	1,  // 11: entities.GitDiff.DiffsEntry.value:type_name -> entities.GitFileDiffs
	11, // 12: entities.StaticDiff.FilesEntry.value:type_name -> entities.FileInfoDiff
	5,  // 13: entities.StaticDiff.DiffsEntry.value:type_name -> entities.StaticFileDiffs
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_entities_git_diff_proto_init() }
func file_entities_git_diff_proto_init() {
	if File_entities_git_diff_proto != nil {
		return
	}
	file_entities_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_git_diff_proto_rawDesc), len(file_entities_git_diff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_git_diff_proto_goTypes,
		DependencyIndexes: file_entities_git_diff_proto_depIdxs,
		MessageInfos:      file_entities_git_diff_proto_msgTypes,
	}.Build()
	File_entities_git_diff_proto = out.File
	file_entities_git_diff_proto_goTypes = nil
	file_entities_git_diff_proto_depIdxs = nil
}
