// Copyright 2022 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: entities/language.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgnosticType int32

const (
	AgnosticType_UNSPECIFIED AgnosticType = 0
	AgnosticType_CLASS       AgnosticType = 1
	AgnosticType_INTERFACE   AgnosticType = 2
	AgnosticType_ENUM        AgnosticType = 3
	AgnosticType_FUNCTION    AgnosticType = 4
	AgnosticType_METHOD      AgnosticType = 5
	AgnosticType_PROPERTY    AgnosticType = 6
	AgnosticType_TYPE        AgnosticType = 7
	AgnosticType_VARIABLE    AgnosticType = 8
	AgnosticType_EXPORT      AgnosticType = 9
	AgnosticType_CONSTANT    AgnosticType = 10
	AgnosticType_CONSTRUCTOR AgnosticType = 11
	AgnosticType_OTHER       AgnosticType = 12
)

// Enum value maps for AgnosticType.
var (
	AgnosticType_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "CLASS",
		2:  "INTERFACE",
		3:  "ENUM",
		4:  "FUNCTION",
		5:  "METHOD",
		6:  "PROPERTY",
		7:  "TYPE",
		8:  "VARIABLE",
		9:  "EXPORT",
		10: "CONSTANT",
		11: "CONSTRUCTOR",
		12: "OTHER",
	}
	AgnosticType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"CLASS":       1,
		"INTERFACE":   2,
		"ENUM":        3,
		"FUNCTION":    4,
		"METHOD":      5,
		"PROPERTY":    6,
		"TYPE":        7,
		"VARIABLE":    8,
		"EXPORT":      9,
		"CONSTANT":    10,
		"CONSTRUCTOR": 11,
		"OTHER":       12,
	}
)

func (x AgnosticType) Enum() *AgnosticType {
	p := new(AgnosticType)
	*p = x
	return p
}

func (x AgnosticType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgnosticType) Descriptor() protoreflect.EnumDescriptor {
	return file_entities_language_proto_enumTypes[0].Descriptor()
}

func (AgnosticType) Type() protoreflect.EnumType {
	return &file_entities_language_proto_enumTypes[0]
}

func (x AgnosticType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgnosticType.Descriptor instead.
func (AgnosticType) EnumDescriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{0}
}

type WordReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          int32                  `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Span          *WordSpan              `protobuf:"bytes,2,opt,name=span,proto3" json:"span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordReference) Reset() {
	*x = WordReference{}
	mi := &file_entities_language_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordReference) ProtoMessage() {}

func (x *WordReference) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordReference.ProtoReflect.Descriptor instead.
func (*WordReference) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{0}
}

func (x *WordReference) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *WordReference) GetSpan() *WordSpan {
	if x != nil {
		return x.Span
	}
	return nil
}

type Symbols struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         map[string]*File       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Symbols       map[string]*Symbol     `protobuf:"bytes,2,rep,name=symbols,proto3" json:"symbols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbols) Reset() {
	*x = Symbols{}
	mi := &file_entities_language_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbols) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbols) ProtoMessage() {}

func (x *Symbols) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbols.ProtoReflect.Descriptor instead.
func (*Symbols) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{1}
}

func (x *Symbols) GetFiles() map[string]*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Symbols) GetSymbols() map[string]*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type Symbol struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Uniquely identifies symbol in analysis
	Id         string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Definition *Definition            `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	Type       string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	FileUsages map[string]*FileUsages `protobuf:"bytes,5,rep,name=fileUsages,proto3" json:"fileUsages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Uniquely identifies symbol in parent. Must not depend on file path, but may change if symbol name or type changes.
	LocalId       string                 `protobuf:"bytes,6,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	TypeRank      int32                  `protobuf:"varint,7,opt,name=type_rank,json=typeRank,proto3" json:"type_rank,omitempty"`
	InnerSymbols  map[string]string      `protobuf:"bytes,8,rep,name=inner_symbols,json=innerSymbols,proto3" json:"inner_symbols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //Local id to global id
	Parent        string                 `protobuf:"bytes,9,opt,name=parent,proto3" json:"parent,omitempty"`                                                                                                           //Parent id
	AgnosticType  AgnosticType           `protobuf:"varint,10,opt,name=agnostic_type,json=agnosticType,proto3,enum=entities.AgnosticType" json:"agnostic_type,omitempty"`
	CodeComments  []*SymbolDocumentation `protobuf:"bytes,11,rep,name=code_comments,json=codeComments,proto3" json:"code_comments,omitempty"`
	Signature     *SymbolDocumentation   `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_entities_language_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{2}
}

func (x *Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Symbol) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Symbol) GetDefinition() *Definition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Symbol) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Symbol) GetFileUsages() map[string]*FileUsages {
	if x != nil {
		return x.FileUsages
	}
	return nil
}

func (x *Symbol) GetLocalId() string {
	if x != nil {
		return x.LocalId
	}
	return ""
}

func (x *Symbol) GetTypeRank() int32 {
	if x != nil {
		return x.TypeRank
	}
	return 0
}

func (x *Symbol) GetInnerSymbols() map[string]string {
	if x != nil {
		return x.InnerSymbols
	}
	return nil
}

func (x *Symbol) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *Symbol) GetAgnosticType() AgnosticType {
	if x != nil {
		return x.AgnosticType
	}
	return AgnosticType_UNSPECIFIED
}

func (x *Symbol) GetCodeComments() []*SymbolDocumentation {
	if x != nil {
		return x.CodeComments
	}
	return nil
}

func (x *Symbol) GetSignature() *SymbolDocumentation {
	if x != nil {
		return x.Signature
	}
	return nil
}

type SymbolDocumentation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Span          *Span                  `protobuf:"bytes,2,opt,name=span,proto3" json:"span,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolDocumentation) Reset() {
	*x = SymbolDocumentation{}
	mi := &file_entities_language_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolDocumentation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolDocumentation) ProtoMessage() {}

func (x *SymbolDocumentation) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolDocumentation.ProtoReflect.Descriptor instead.
func (*SymbolDocumentation) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{3}
}

func (x *SymbolDocumentation) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SymbolDocumentation) GetSpan() *Span {
	if x != nil {
		return x.Span
	}
	return nil
}

type FileUsages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Imports       []*ReferenceBlock      `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports,omitempty"`
	Usages        []*ReferenceBlock      `protobuf:"bytes,3,rep,name=usages,proto3" json:"usages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUsages) Reset() {
	*x = FileUsages{}
	mi := &file_entities_language_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUsages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUsages) ProtoMessage() {}

func (x *FileUsages) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUsages.ProtoReflect.Descriptor instead.
func (*FileUsages) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{4}
}

func (x *FileUsages) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileUsages) GetImports() []*ReferenceBlock {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *FileUsages) GetUsages() []*ReferenceBlock {
	if x != nil {
		return x.Usages
	}
	return nil
}

type Context struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         string                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	Block         *Span                  `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Context) Reset() {
	*x = Context{}
	mi := &file_entities_language_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Context) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Context) ProtoMessage() {}

func (x *Context) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Context.ProtoReflect.Descriptor instead.
func (*Context) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{5}
}

func (x *Context) GetChunk() string {
	if x != nil {
		return x.Chunk
	}
	return ""
}

func (x *Context) GetBlock() *Span {
	if x != nil {
		return x.Block
	}
	return nil
}

type Definition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FilePath       string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	MainDefinition *ReferenceBlock        `protobuf:"bytes,2,opt,name=main_definition,json=mainDefinition,proto3" json:"main_definition,omitempty"`
	Declarations   []*ReferenceBlock      `protobuf:"bytes,3,rep,name=declarations,proto3" json:"declarations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Definition) Reset() {
	*x = Definition{}
	mi := &file_entities_language_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Definition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Definition) ProtoMessage() {}

func (x *Definition) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Definition.ProtoReflect.Descriptor instead.
func (*Definition) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{6}
}

func (x *Definition) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *Definition) GetMainDefinition() *ReferenceBlock {
	if x != nil {
		return x.MainDefinition
	}
	return nil
}

func (x *Definition) GetDeclarations() []*ReferenceBlock {
	if x != nil {
		return x.Declarations
	}
	return nil
}

type ReferenceBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *Context               `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Reference     *WordReference         `protobuf:"bytes,2,opt,name=reference,proto3" json:"reference,omitempty"`
	Signature     *SpanAST               `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Body          *SpanAST               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceBlock) Reset() {
	*x = ReferenceBlock{}
	mi := &file_entities_language_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceBlock) ProtoMessage() {}

func (x *ReferenceBlock) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceBlock.ProtoReflect.Descriptor instead.
func (*ReferenceBlock) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{7}
}

func (x *ReferenceBlock) GetContext() *Context {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReferenceBlock) GetReference() *WordReference {
	if x != nil {
		return x.Reference
	}
	return nil
}

func (x *ReferenceBlock) GetSignature() *SpanAST {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ReferenceBlock) GetBody() *SpanAST {
	if x != nil {
		return x.Body
	}
	return nil
}

type SpanAST struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AstTokens     []string               `protobuf:"bytes,1,rep,name=ast_tokens,json=astTokens,proto3" json:"ast_tokens,omitempty"`
	Block         *Span                  `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpanAST) Reset() {
	*x = SpanAST{}
	mi := &file_entities_language_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpanAST) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpanAST) ProtoMessage() {}

func (x *SpanAST) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpanAST.ProtoReflect.Descriptor instead.
func (*SpanAST) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{8}
}

func (x *SpanAST) GetAstTokens() []string {
	if x != nil {
		return x.AstTokens
	}
	return nil
}

func (x *SpanAST) GetBlock() *Span {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *SpanAST) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BlobId        string                 `protobuf:"bytes,2,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	NumLines      int32                  `protobuf:"varint,3,opt,name=num_lines,json=numLines,proto3" json:"num_lines,omitempty"`
	Symbols       map[string]string      `protobuf:"bytes,4,rep,name=symbols,proto3" json:"symbols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //Local id to symbol id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_entities_language_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_entities_language_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_entities_language_proto_rawDescGZIP(), []int{9}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *File) GetNumLines() int32 {
	if x != nil {
		return x.NumLines
	}
	return 0
}

func (x *File) GetSymbols() map[string]string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_entities_language_proto protoreflect.FileDescriptor

const file_entities_language_proto_rawDesc = "" +
	"\n" +
	"\x17entities/language.proto\x12\bentities\x1a\x13entities/span.proto\"K\n" +
	"\rWordReference\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x05R\x04line\x12&\n" +
	"\x04span\x18\x02 \x01(\v2\x12.entities.WordSpanR\x04span\"\x8f\x02\n" +
	"\aSymbols\x122\n" +
	"\x05files\x18\x01 \x03(\v2\x1c.entities.Symbols.FilesEntryR\x05files\x128\n" +
	"\asymbols\x18\x02 \x03(\v2\x1e.entities.Symbols.SymbolsEntryR\asymbols\x1aH\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.entities.FileR\x05value:\x028\x01\x1aL\n" +
	"\fSymbolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.entities.SymbolR\x05value:\x028\x01\"\xa5\x05\n" +
	"\x06Symbol\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x124\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2\x14.entities.DefinitionR\n" +
	"definition\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12@\n" +
	"\n" +
	"fileUsages\x18\x05 \x03(\v2 .entities.Symbol.FileUsagesEntryR\n" +
	"fileUsages\x12\x19\n" +
	"\blocal_id\x18\x06 \x01(\tR\alocalId\x12\x1b\n" +
	"\ttype_rank\x18\a \x01(\x05R\btypeRank\x12G\n" +
	"\rinner_symbols\x18\b \x03(\v2\".entities.Symbol.InnerSymbolsEntryR\finnerSymbols\x12\x16\n" +
	"\x06parent\x18\t \x01(\tR\x06parent\x12;\n" +
	"\ragnostic_type\x18\n" +
	" \x01(\x0e2\x16.entities.AgnosticTypeR\fagnosticType\x12B\n" +
	"\rcode_comments\x18\v \x03(\v2\x1d.entities.SymbolDocumentationR\fcodeComments\x12;\n" +
	"\tsignature\x18\f \x01(\v2\x1d.entities.SymbolDocumentationR\tsignature\x1aS\n" +
	"\x0fFileUsagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.entities.FileUsagesR\x05value:\x028\x01\x1a?\n" +
	"\x11InnerSymbolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x13SymbolDocumentation\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\"\n" +
	"\x04span\x18\x02 \x01(\v2\x0e.entities.SpanR\x04span\"\x8f\x01\n" +
	"\n" +
	"FileUsages\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x122\n" +
	"\aimports\x18\x02 \x03(\v2\x18.entities.ReferenceBlockR\aimports\x120\n" +
	"\x06usages\x18\x03 \x03(\v2\x18.entities.ReferenceBlockR\x06usages\"E\n" +
	"\aContext\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\tR\x05chunk\x12$\n" +
	"\x05block\x18\x02 \x01(\v2\x0e.entities.SpanR\x05block\"\xaa\x01\n" +
	"\n" +
	"Definition\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12A\n" +
	"\x0fmain_definition\x18\x02 \x01(\v2\x18.entities.ReferenceBlockR\x0emainDefinition\x12<\n" +
	"\fdeclarations\x18\x03 \x03(\v2\x18.entities.ReferenceBlockR\fdeclarations\"\xcc\x01\n" +
	"\x0eReferenceBlock\x12+\n" +
	"\acontext\x18\x01 \x01(\v2\x11.entities.ContextR\acontext\x125\n" +
	"\treference\x18\x02 \x01(\v2\x17.entities.WordReferenceR\treference\x12/\n" +
	"\tsignature\x18\x03 \x01(\v2\x11.entities.SpanASTR\tsignature\x12%\n" +
	"\x04body\x18\x04 \x01(\v2\x11.entities.SpanASTR\x04body\"b\n" +
	"\aSpanAST\x12\x1d\n" +
	"\n" +
	"ast_tokens\x18\x01 \x03(\tR\tastTokens\x12$\n" +
	"\x05block\x18\x02 \x01(\v2\x0e.entities.SpanR\x05block\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"\xc3\x01\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x17\n" +
	"\ablob_id\x18\x02 \x01(\tR\x06blobId\x12\x1b\n" +
	"\tnum_lines\x18\x03 \x01(\x05R\bnumLines\x125\n" +
	"\asymbols\x18\x04 \x03(\v2\x1b.entities.File.SymbolsEntryR\asymbols\x1a:\n" +
	"\fSymbolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xb9\x01\n" +
	"\fAgnosticType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\t\n" +
	"\x05CLASS\x10\x01\x12\r\n" +
	"\tINTERFACE\x10\x02\x12\b\n" +
	"\x04ENUM\x10\x03\x12\f\n" +
	"\bFUNCTION\x10\x04\x12\n" +
	"\n" +
	"\x06METHOD\x10\x05\x12\f\n" +
	"\bPROPERTY\x10\x06\x12\b\n" +
	"\x04TYPE\x10\a\x12\f\n" +
	"\bVARIABLE\x10\b\x12\n" +
	"\n" +
	"\x06EXPORT\x10\t\x12\f\n" +
	"\bCONSTANT\x10\n" +
	"\x12\x0f\n" +
	"\vCONSTRUCTOR\x10\v\x12\t\n" +
	"\x05OTHER\x10\fB&Z$github.com/reviewpad/api/go/entitiesb\x06proto3"

var (
	file_entities_language_proto_rawDescOnce sync.Once
	file_entities_language_proto_rawDescData []byte
)

func file_entities_language_proto_rawDescGZIP() []byte {
	file_entities_language_proto_rawDescOnce.Do(func() {
		file_entities_language_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_language_proto_rawDesc), len(file_entities_language_proto_rawDesc)))
	})
	return file_entities_language_proto_rawDescData
}

var file_entities_language_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_entities_language_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_entities_language_proto_goTypes = []any{
	(AgnosticType)(0),           // 0: entities.AgnosticType
	(*WordReference)(nil),       // 1: entities.WordReference
	(*Symbols)(nil),             // 2: entities.Symbols
	(*Symbol)(nil),              // 3: entities.Symbol
	(*SymbolDocumentation)(nil), // 4: entities.SymbolDocumentation
	(*FileUsages)(nil),          // 5: entities.FileUsages
	(*Context)(nil),             // 6: entities.Context
	(*Definition)(nil),          // 7: entities.Definition
	(*ReferenceBlock)(nil),      // 8: entities.ReferenceBlock
	(*SpanAST)(nil),             // 9: entities.SpanAST
	(*File)(nil),                // 10: entities.File
	nil,                         // 11: entities.Symbols.FilesEntry
	nil,                         // 12: entities.Symbols.SymbolsEntry
	nil,                         // 13: entities.Symbol.FileUsagesEntry
	nil,                         // 14: entities.Symbol.InnerSymbolsEntry
	nil,                         // 15: entities.File.SymbolsEntry
	(*WordSpan)(nil),            // 16: entities.WordSpan
	(*Span)(nil),                // 17: entities.Span
}
var file_entities_language_proto_depIdxs = []int32{
	16, // 0: entities.WordReference.span:type_name -> entities.WordSpan
	11, // 1: entities.Symbols.files:type_name -> entities.Symbols.FilesEntry
	12, // 2: entities.Symbols.symbols:type_name -> entities.Symbols.SymbolsEntry
	7,  // 3: entities.Symbol.definition:type_name -> entities.Definition
	13, // 4: entities.Symbol.fileUsages:type_name -> entities.Symbol.FileUsagesEntry
	14, // 5: entities.Symbol.inner_symbols:type_name -> entities.Symbol.InnerSymbolsEntry
	0,  // 6: entities.Symbol.agnostic_type:type_name -> entities.AgnosticType
	4,  // 7: entities.Symbol.code_comments:type_name -> entities.SymbolDocumentation
	4,  // 8: entities.Symbol.signature:type_name -> entities.SymbolDocumentation
	17, // 9: entities.SymbolDocumentation.span:type_name -> entities.Span
	8,  // 10: entities.FileUsages.imports:type_name -> entities.ReferenceBlock
	8,  // 11: entities.FileUsages.usages:type_name -> entities.ReferenceBlock
	17, // 12: entities.Context.block:type_name -> entities.Span
	8,  // 13: entities.Definition.main_definition:type_name -> entities.ReferenceBlock
	8,  // 14: entities.Definition.declarations:type_name -> entities.ReferenceBlock
	6,  // 15: entities.ReferenceBlock.context:type_name -> entities.Context
	1,  // 16: entities.ReferenceBlock.reference:type_name -> entities.WordReference
	9,  // 17: entities.ReferenceBlock.signature:type_name -> entities.SpanAST
	9,  // 18: entities.ReferenceBlock.body:type_name -> entities.SpanAST
	17, // 19: entities.SpanAST.block:type_name -> entities.Span
	15, // 20: entities.File.symbols:type_name -> entities.File.SymbolsEntry
	10, // 21: entities.Symbols.FilesEntry.value:type_name -> entities.File
	3,  // 22: entities.Symbols.SymbolsEntry.value:type_name -> entities.Symbol
	5,  // 23: entities.Symbol.FileUsagesEntry.value:type_name -> entities.FileUsages
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_entities_language_proto_init() }
func file_entities_language_proto_init() {
	if File_entities_language_proto != nil {
		return
	}
	file_entities_span_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_language_proto_rawDesc), len(file_entities_language_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_language_proto_goTypes,
		DependencyIndexes: file_entities_language_proto_depIdxs,
		EnumInfos:         file_entities_language_proto_enumTypes,
		MessageInfos:      file_entities_language_proto_msgTypes,
	}.Build()
	File_entities_language_proto = out.File
	file_entities_language_proto_goTypes = nil
	file_entities_language_proto_depIdxs = nil
}
