// Copyright 2022 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: entities/span.proto

package entities

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Span struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *Location              `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *Location              `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_entities_span_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_entities_span_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_entities_span_proto_rawDescGZIP(), []int{0}
}

func (x *Span) GetStart() *Location {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Span) GetEnd() *Location {
	if x != nil {
		return x.End
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          int32                  `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_entities_span_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_entities_span_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_entities_span_proto_rawDescGZIP(), []int{1}
}

func (x *Location) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Location) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type WordSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartColumn   int32                  `protobuf:"varint,1,opt,name=start_column,json=startColumn,proto3" json:"start_column,omitempty"`
	EndColumn     int32                  `protobuf:"varint,2,opt,name=end_column,json=endColumn,proto3" json:"end_column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WordSpan) Reset() {
	*x = WordSpan{}
	mi := &file_entities_span_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WordSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordSpan) ProtoMessage() {}

func (x *WordSpan) ProtoReflect() protoreflect.Message {
	mi := &file_entities_span_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordSpan.ProtoReflect.Descriptor instead.
func (*WordSpan) Descriptor() ([]byte, []int) {
	return file_entities_span_proto_rawDescGZIP(), []int{2}
}

func (x *WordSpan) GetStartColumn() int32 {
	if x != nil {
		return x.StartColumn
	}
	return 0
}

func (x *WordSpan) GetEndColumn() int32 {
	if x != nil {
		return x.EndColumn
	}
	return 0
}

var File_entities_span_proto protoreflect.FileDescriptor

const file_entities_span_proto_rawDesc = "" +
	"\n" +
	"\x13entities/span.proto\x12\bentities\"V\n" +
	"\x04Span\x12(\n" +
	"\x05start\x18\x01 \x01(\v2\x12.entities.LocationR\x05start\x12$\n" +
	"\x03end\x18\x02 \x01(\v2\x12.entities.LocationR\x03end\"6\n" +
	"\bLocation\x12\x12\n" +
	"\x04line\x18\x01 \x01(\x05R\x04line\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"L\n" +
	"\bWordSpan\x12!\n" +
	"\fstart_column\x18\x01 \x01(\x05R\vstartColumn\x12\x1d\n" +
	"\n" +
	"end_column\x18\x02 \x01(\x05R\tendColumnB&Z$github.com/reviewpad/api/go/entitiesb\x06proto3"

var (
	file_entities_span_proto_rawDescOnce sync.Once
	file_entities_span_proto_rawDescData []byte
)

func file_entities_span_proto_rawDescGZIP() []byte {
	file_entities_span_proto_rawDescOnce.Do(func() {
		file_entities_span_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_entities_span_proto_rawDesc), len(file_entities_span_proto_rawDesc)))
	})
	return file_entities_span_proto_rawDescData
}

var file_entities_span_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_entities_span_proto_goTypes = []any{
	(*Span)(nil),     // 0: entities.Span
	(*Location)(nil), // 1: entities.Location
	(*WordSpan)(nil), // 2: entities.WordSpan
}
var file_entities_span_proto_depIdxs = []int32{
	1, // 0: entities.Span.start:type_name -> entities.Location
	1, // 1: entities.Span.end:type_name -> entities.Location
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_entities_span_proto_init() }
func file_entities_span_proto_init() {
	if File_entities_span_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_entities_span_proto_rawDesc), len(file_entities_span_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_span_proto_goTypes,
		DependencyIndexes: file_entities_span_proto_depIdxs,
		MessageInfos:      file_entities_span_proto_msgTypes,
	}.Build()
	File_entities_span_proto = out.File
	file_entities_span_proto_goTypes = nil
	file_entities_span_proto_depIdxs = nil
}
