// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: services/diff.proto

package services

import (
	entities "github.com/reviewpad/api/go/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDefinedSymbolsDiffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoUri       string                 `protobuf:"bytes,1,opt,name=repo_uri,json=repoUri,proto3" json:"repo_uri,omitempty"`
	Old           *entities.Symbols      `protobuf:"bytes,2,opt,name=old,proto3" json:"old,omitempty"`
	New           *entities.Symbols      `protobuf:"bytes,3,opt,name=new,proto3" json:"new,omitempty"`
	GitDiff       *entities.GitDiff      `protobuf:"bytes,4,opt,name=git_diff,json=gitDiff,proto3" json:"git_diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinedSymbolsDiffRequest) Reset() {
	*x = GetDefinedSymbolsDiffRequest{}
	mi := &file_services_diff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinedSymbolsDiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinedSymbolsDiffRequest) ProtoMessage() {}

func (x *GetDefinedSymbolsDiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_diff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinedSymbolsDiffRequest.ProtoReflect.Descriptor instead.
func (*GetDefinedSymbolsDiffRequest) Descriptor() ([]byte, []int) {
	return file_services_diff_proto_rawDescGZIP(), []int{0}
}

func (x *GetDefinedSymbolsDiffRequest) GetRepoUri() string {
	if x != nil {
		return x.RepoUri
	}
	return ""
}

func (x *GetDefinedSymbolsDiffRequest) GetOld() *entities.Symbols {
	if x != nil {
		return x.Old
	}
	return nil
}

func (x *GetDefinedSymbolsDiffRequest) GetNew() *entities.Symbols {
	if x != nil {
		return x.New
	}
	return nil
}

func (x *GetDefinedSymbolsDiffRequest) GetGitDiff() *entities.GitDiff {
	if x != nil {
		return x.GitDiff
	}
	return nil
}

type GetDefinedSymbolsDiffReply struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Symbols       map[string]*entities.SymbolDiff `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` //Map from symbol id to symbol
	Roots         []string                        `protobuf:"bytes,2,rep,name=roots,proto3" json:"roots,omitempty"`                                                                               //Roots of the symbol tree
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefinedSymbolsDiffReply) Reset() {
	*x = GetDefinedSymbolsDiffReply{}
	mi := &file_services_diff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefinedSymbolsDiffReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefinedSymbolsDiffReply) ProtoMessage() {}

func (x *GetDefinedSymbolsDiffReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_diff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefinedSymbolsDiffReply.ProtoReflect.Descriptor instead.
func (*GetDefinedSymbolsDiffReply) Descriptor() ([]byte, []int) {
	return file_services_diff_proto_rawDescGZIP(), []int{1}
}

func (x *GetDefinedSymbolsDiffReply) GetSymbols() map[string]*entities.SymbolDiff {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *GetDefinedSymbolsDiffReply) GetRoots() []string {
	if x != nil {
		return x.Roots
	}
	return nil
}

var File_services_diff_proto protoreflect.FileDescriptor

const file_services_diff_proto_rawDesc = "" +
	"\n" +
	"\x13services/diff.proto\x12\bservices\x1a\x17entities/language.proto\x1a\x1centities/semantic_diff.proto\x1a\x17entities/git_diff.proto\"\xb1\x01\n" +
	"\x1cGetDefinedSymbolsDiffRequest\x12\x19\n" +
	"\brepo_uri\x18\x01 \x01(\tR\arepoUri\x12#\n" +
	"\x03old\x18\x02 \x01(\v2\x11.entities.SymbolsR\x03old\x12#\n" +
	"\x03new\x18\x03 \x01(\v2\x11.entities.SymbolsR\x03new\x12,\n" +
	"\bgit_diff\x18\x04 \x01(\v2\x11.entities.GitDiffR\agitDiff\"\xd1\x01\n" +
	"\x1aGetDefinedSymbolsDiffReply\x12K\n" +
	"\asymbols\x18\x01 \x03(\v21.services.GetDefinedSymbolsDiffReply.SymbolsEntryR\asymbols\x12\x14\n" +
	"\x05roots\x18\x02 \x03(\tR\x05roots\x1aP\n" +
	"\fSymbolsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.entities.SymbolDiffR\x05value:\x028\x012o\n" +
	"\x04Diff\x12g\n" +
	"\x15GetDefinedSymbolsDiff\x12&.services.GetDefinedSymbolsDiffRequest\x1a$.services.GetDefinedSymbolsDiffReply\"\x00B&Z$github.com/reviewpad/api/go/servicesb\x06proto3"

var (
	file_services_diff_proto_rawDescOnce sync.Once
	file_services_diff_proto_rawDescData []byte
)

func file_services_diff_proto_rawDescGZIP() []byte {
	file_services_diff_proto_rawDescOnce.Do(func() {
		file_services_diff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_diff_proto_rawDesc), len(file_services_diff_proto_rawDesc)))
	})
	return file_services_diff_proto_rawDescData
}

var file_services_diff_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_diff_proto_goTypes = []any{
	(*GetDefinedSymbolsDiffRequest)(nil), // 0: services.GetDefinedSymbolsDiffRequest
	(*GetDefinedSymbolsDiffReply)(nil),   // 1: services.GetDefinedSymbolsDiffReply
	nil,                                  // 2: services.GetDefinedSymbolsDiffReply.SymbolsEntry
	(*entities.Symbols)(nil),             // 3: entities.Symbols
	(*entities.GitDiff)(nil),             // 4: entities.GitDiff
	(*entities.SymbolDiff)(nil),          // 5: entities.SymbolDiff
}
var file_services_diff_proto_depIdxs = []int32{
	3, // 0: services.GetDefinedSymbolsDiffRequest.old:type_name -> entities.Symbols
	3, // 1: services.GetDefinedSymbolsDiffRequest.new:type_name -> entities.Symbols
	4, // 2: services.GetDefinedSymbolsDiffRequest.git_diff:type_name -> entities.GitDiff
	2, // 3: services.GetDefinedSymbolsDiffReply.symbols:type_name -> services.GetDefinedSymbolsDiffReply.SymbolsEntry
	5, // 4: services.GetDefinedSymbolsDiffReply.SymbolsEntry.value:type_name -> entities.SymbolDiff
	0, // 5: services.Diff.GetDefinedSymbolsDiff:input_type -> services.GetDefinedSymbolsDiffRequest
	1, // 6: services.Diff.GetDefinedSymbolsDiff:output_type -> services.GetDefinedSymbolsDiffReply
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_services_diff_proto_init() }
func file_services_diff_proto_init() {
	if File_services_diff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_diff_proto_rawDesc), len(file_services_diff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_diff_proto_goTypes,
		DependencyIndexes: file_services_diff_proto_depIdxs,
		MessageInfos:      file_services_diff_proto_msgTypes,
	}.Build()
	File_services_diff_proto = out.File
	file_services_diff_proto_goTypes = nil
	file_services_diff_proto_depIdxs = nil
}
