// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: services/robin.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Robin_ChatInCodeHost_FullMethodName = "/services.Robin/ChatInCodeHost"
	Robin_Explain_FullMethodName        = "/services.Robin/Explain"
	Robin_Prompt_FullMethodName         = "/services.Robin/Prompt"
	Robin_RawPrompt_FullMethodName      = "/services.Robin/RawPrompt"
	Robin_Summarize_FullMethodName      = "/services.Robin/Summarize"
)

// RobinClient is the client API for Robin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RobinClient interface {
	ChatInCodeHost(ctx context.Context, in *ChatInCodeHostRequest, opts ...grpc.CallOption) (*ChatInCodeHostReply, error)
	Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainReply, error)
	Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptReply, error)
	RawPrompt(ctx context.Context, in *RawPromptRequest, opts ...grpc.CallOption) (*PromptReply, error)
	Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeReply, error)
}

type robinClient struct {
	cc grpc.ClientConnInterface
}

func NewRobinClient(cc grpc.ClientConnInterface) RobinClient {
	return &robinClient{cc}
}

func (c *robinClient) ChatInCodeHost(ctx context.Context, in *ChatInCodeHostRequest, opts ...grpc.CallOption) (*ChatInCodeHostReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatInCodeHostReply)
	err := c.cc.Invoke(ctx, Robin_ChatInCodeHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robinClient) Explain(ctx context.Context, in *ExplainRequest, opts ...grpc.CallOption) (*ExplainReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainReply)
	err := c.cc.Invoke(ctx, Robin_Explain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robinClient) Prompt(ctx context.Context, in *PromptRequest, opts ...grpc.CallOption) (*PromptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptReply)
	err := c.cc.Invoke(ctx, Robin_Prompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robinClient) RawPrompt(ctx context.Context, in *RawPromptRequest, opts ...grpc.CallOption) (*PromptReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptReply)
	err := c.cc.Invoke(ctx, Robin_RawPrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robinClient) Summarize(ctx context.Context, in *SummarizeRequest, opts ...grpc.CallOption) (*SummarizeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeReply)
	err := c.cc.Invoke(ctx, Robin_Summarize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobinServer is the server API for Robin service.
// All implementations must embed UnimplementedRobinServer
// for forward compatibility.
type RobinServer interface {
	ChatInCodeHost(context.Context, *ChatInCodeHostRequest) (*ChatInCodeHostReply, error)
	Explain(context.Context, *ExplainRequest) (*ExplainReply, error)
	Prompt(context.Context, *PromptRequest) (*PromptReply, error)
	RawPrompt(context.Context, *RawPromptRequest) (*PromptReply, error)
	Summarize(context.Context, *SummarizeRequest) (*SummarizeReply, error)
	mustEmbedUnimplementedRobinServer()
}

// UnimplementedRobinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRobinServer struct{}

func (UnimplementedRobinServer) ChatInCodeHost(context.Context, *ChatInCodeHostRequest) (*ChatInCodeHostReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ChatInCodeHost not implemented")
}
func (UnimplementedRobinServer) Explain(context.Context, *ExplainRequest) (*ExplainReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Explain not implemented")
}
func (UnimplementedRobinServer) Prompt(context.Context, *PromptRequest) (*PromptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Prompt not implemented")
}
func (UnimplementedRobinServer) RawPrompt(context.Context, *RawPromptRequest) (*PromptReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RawPrompt not implemented")
}
func (UnimplementedRobinServer) Summarize(context.Context, *SummarizeRequest) (*SummarizeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Summarize not implemented")
}
func (UnimplementedRobinServer) mustEmbedUnimplementedRobinServer() {}
func (UnimplementedRobinServer) testEmbeddedByValue()               {}

// UnsafeRobinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RobinServer will
// result in compilation errors.
type UnsafeRobinServer interface {
	mustEmbedUnimplementedRobinServer()
}

func RegisterRobinServer(s grpc.ServiceRegistrar, srv RobinServer) {
	// If the following call panics, it indicates UnimplementedRobinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Robin_ServiceDesc, srv)
}

func _Robin_ChatInCodeHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatInCodeHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobinServer).ChatInCodeHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robin_ChatInCodeHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobinServer).ChatInCodeHost(ctx, req.(*ChatInCodeHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robin_Explain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobinServer).Explain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robin_Explain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobinServer).Explain(ctx, req.(*ExplainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robin_Prompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobinServer).Prompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robin_Prompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobinServer).Prompt(ctx, req.(*PromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robin_RawPrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobinServer).RawPrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robin_RawPrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobinServer).RawPrompt(ctx, req.(*RawPromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Robin_Summarize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobinServer).Summarize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Robin_Summarize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobinServer).Summarize(ctx, req.(*SummarizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Robin_ServiceDesc is the grpc.ServiceDesc for Robin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Robin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.Robin",
	HandlerType: (*RobinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatInCodeHost",
			Handler:    _Robin_ChatInCodeHost_Handler,
		},
		{
			MethodName: "Explain",
			Handler:    _Robin_Explain_Handler,
		},
		{
			MethodName: "Prompt",
			Handler:    _Robin_Prompt_Handler,
		},
		{
			MethodName: "RawPrompt",
			Handler:    _Robin_RawPrompt_Handler,
		},
		{
			MethodName: "Summarize",
			Handler:    _Robin_Summarize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/robin.proto",
}
