// Copyright 2023 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: services/robin.proto

package services

import (
	entities "github.com/reviewpad/api/go/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatInCodeHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Target        *entities.TargetEntity `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInCodeHostRequest) Reset() {
	*x = ChatInCodeHostRequest{}
	mi := &file_services_robin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInCodeHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInCodeHostRequest) ProtoMessage() {}

func (x *ChatInCodeHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInCodeHostRequest.ProtoReflect.Descriptor instead.
func (*ChatInCodeHostRequest) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{0}
}

func (x *ChatInCodeHostRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ChatInCodeHostRequest) GetTarget() *entities.TargetEntity {
	if x != nil {
		return x.Target
	}
	return nil
}

type ChatInCodeHostReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatInCodeHostReply) Reset() {
	*x = ChatInCodeHostReply{}
	mi := &file_services_robin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInCodeHostReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInCodeHostReply) ProtoMessage() {}

func (x *ChatInCodeHostReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInCodeHostReply.ProtoReflect.Descriptor instead.
func (*ChatInCodeHostReply) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{1}
}

func (x *ChatInCodeHostReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type ExplainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Target        *entities.TargetEntity `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	CommentId     string                 `protobuf:"bytes,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Act           bool                   `protobuf:"varint,4,opt,name=act,proto3" json:"act,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainRequest) Reset() {
	*x = ExplainRequest{}
	mi := &file_services_robin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainRequest) ProtoMessage() {}

func (x *ExplainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainRequest.ProtoReflect.Descriptor instead.
func (*ExplainRequest) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{2}
}

func (x *ExplainRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ExplainRequest) GetTarget() *entities.TargetEntity {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ExplainRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *ExplainRequest) GetAct() bool {
	if x != nil {
		return x.Act
	}
	return false
}

func (x *ExplainRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type ExplainReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Explanation   string                 `protobuf:"bytes,1,opt,name=explanation,proto3" json:"explanation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainReply) Reset() {
	*x = ExplainReply{}
	mi := &file_services_robin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainReply) ProtoMessage() {}

func (x *ExplainReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainReply.ProtoReflect.Descriptor instead.
func (*ExplainReply) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{3}
}

func (x *ExplainReply) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Target        *entities.TargetEntity `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Prompt        string                 `protobuf:"bytes,3,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Act           bool                   `protobuf:"varint,4,opt,name=act,proto3" json:"act,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_services_robin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{4}
}

func (x *PromptRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PromptRequest) GetTarget() *entities.TargetEntity {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *PromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *PromptRequest) GetAct() bool {
	if x != nil {
		return x.Act
	}
	return false
}

func (x *PromptRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type PromptReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptReply) Reset() {
	*x = PromptReply{}
	mi := &file_services_robin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptReply) ProtoMessage() {}

func (x *PromptReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptReply.ProtoReflect.Descriptor instead.
func (*PromptReply) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{5}
}

func (x *PromptReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type RawPromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Target        *entities.TargetEntity `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	UserPrompt    string                 `protobuf:"bytes,4,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`
	Act           bool                   `protobuf:"varint,5,opt,name=act,proto3" json:"act,omitempty"`
	Model         string                 `protobuf:"bytes,6,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RawPromptRequest) Reset() {
	*x = RawPromptRequest{}
	mi := &file_services_robin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RawPromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RawPromptRequest) ProtoMessage() {}

func (x *RawPromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RawPromptRequest.ProtoReflect.Descriptor instead.
func (*RawPromptRequest) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{6}
}

func (x *RawPromptRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RawPromptRequest) GetTarget() *entities.TargetEntity {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RawPromptRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *RawPromptRequest) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *RawPromptRequest) GetAct() bool {
	if x != nil {
		return x.Act
	}
	return false
}

func (x *RawPromptRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SummarizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Target        *entities.TargetEntity `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Act           bool                   `protobuf:"varint,3,opt,name=act,proto3" json:"act,omitempty"`
	Extended      bool                   `protobuf:"varint,4,opt,name=extended,proto3" json:"extended,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeRequest) Reset() {
	*x = SummarizeRequest{}
	mi := &file_services_robin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeRequest) ProtoMessage() {}

func (x *SummarizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeRequest.ProtoReflect.Descriptor instead.
func (*SummarizeRequest) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{7}
}

func (x *SummarizeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SummarizeRequest) GetTarget() *entities.TargetEntity {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *SummarizeRequest) GetAct() bool {
	if x != nil {
		return x.Act
	}
	return false
}

func (x *SummarizeRequest) GetExtended() bool {
	if x != nil {
		return x.Extended
	}
	return false
}

func (x *SummarizeRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SummarizeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummarizeReply) Reset() {
	*x = SummarizeReply{}
	mi := &file_services_robin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummarizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummarizeReply) ProtoMessage() {}

func (x *SummarizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_robin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummarizeReply.ProtoReflect.Descriptor instead.
func (*SummarizeReply) Descriptor() ([]byte, []int) {
	return file_services_robin_proto_rawDescGZIP(), []int{8}
}

func (x *SummarizeReply) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

var File_services_robin_proto protoreflect.FileDescriptor

const file_services_robin_proto_rawDesc = "" +
	"\n" +
	"\x14services/robin.proto\x12\bservices\x1a\x1centities/target_entity.proto\"]\n" +
	"\x15ChatInCodeHostRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.entities.TargetEntityR\x06target\"+\n" +
	"\x13ChatInCodeHostReply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"\x9d\x01\n" +
	"\x0eExplainRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.entities.TargetEntityR\x06target\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\tR\tcommentId\x12\x10\n" +
	"\x03act\x18\x04 \x01(\bR\x03act\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"0\n" +
	"\fExplainReply\x12 \n" +
	"\vexplanation\x18\x01 \x01(\tR\vexplanation\"\x95\x01\n" +
	"\rPromptRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.entities.TargetEntityR\x06target\x12\x16\n" +
	"\x06prompt\x18\x03 \x01(\tR\x06prompt\x12\x10\n" +
	"\x03act\x18\x04 \x01(\bR\x03act\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"#\n" +
	"\vPromptReply\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply\"\xc6\x01\n" +
	"\x10RawPromptRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.entities.TargetEntityR\x06target\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x1f\n" +
	"\vuser_prompt\x18\x04 \x01(\tR\n" +
	"userPrompt\x12\x10\n" +
	"\x03act\x18\x05 \x01(\bR\x03act\x12\x14\n" +
	"\x05model\x18\x06 \x01(\tR\x05model\"\x9c\x01\n" +
	"\x10SummarizeRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.entities.TargetEntityR\x06target\x12\x10\n" +
	"\x03act\x18\x03 \x01(\bR\x03act\x12\x1a\n" +
	"\bextended\x18\x04 \x01(\bR\bextended\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"*\n" +
	"\x0eSummarizeReply\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary2\xdd\x02\n" +
	"\x05Robin\x12R\n" +
	"\x0eChatInCodeHost\x12\x1f.services.ChatInCodeHostRequest\x1a\x1d.services.ChatInCodeHostReply\"\x00\x12=\n" +
	"\aExplain\x12\x18.services.ExplainRequest\x1a\x16.services.ExplainReply\"\x00\x12:\n" +
	"\x06Prompt\x12\x17.services.PromptRequest\x1a\x15.services.PromptReply\"\x00\x12@\n" +
	"\tRawPrompt\x12\x1a.services.RawPromptRequest\x1a\x15.services.PromptReply\"\x00\x12C\n" +
	"\tSummarize\x12\x1a.services.SummarizeRequest\x1a\x18.services.SummarizeReply\"\x00B&Z$github.com/reviewpad/api/go/servicesb\x06proto3"

var (
	file_services_robin_proto_rawDescOnce sync.Once
	file_services_robin_proto_rawDescData []byte
)

func file_services_robin_proto_rawDescGZIP() []byte {
	file_services_robin_proto_rawDescOnce.Do(func() {
		file_services_robin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_robin_proto_rawDesc), len(file_services_robin_proto_rawDesc)))
	})
	return file_services_robin_proto_rawDescData
}

var file_services_robin_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_services_robin_proto_goTypes = []any{
	(*ChatInCodeHostRequest)(nil), // 0: services.ChatInCodeHostRequest
	(*ChatInCodeHostReply)(nil),   // 1: services.ChatInCodeHostReply
	(*ExplainRequest)(nil),        // 2: services.ExplainRequest
	(*ExplainReply)(nil),          // 3: services.ExplainReply
	(*PromptRequest)(nil),         // 4: services.PromptRequest
	(*PromptReply)(nil),           // 5: services.PromptReply
	(*RawPromptRequest)(nil),      // 6: services.RawPromptRequest
	(*SummarizeRequest)(nil),      // 7: services.SummarizeRequest
	(*SummarizeReply)(nil),        // 8: services.SummarizeReply
	(*entities.TargetEntity)(nil), // 9: entities.TargetEntity
}
var file_services_robin_proto_depIdxs = []int32{
	9,  // 0: services.ChatInCodeHostRequest.target:type_name -> entities.TargetEntity
	9,  // 1: services.ExplainRequest.target:type_name -> entities.TargetEntity
	9,  // 2: services.PromptRequest.target:type_name -> entities.TargetEntity
	9,  // 3: services.RawPromptRequest.target:type_name -> entities.TargetEntity
	9,  // 4: services.SummarizeRequest.target:type_name -> entities.TargetEntity
	0,  // 5: services.Robin.ChatInCodeHost:input_type -> services.ChatInCodeHostRequest
	2,  // 6: services.Robin.Explain:input_type -> services.ExplainRequest
	4,  // 7: services.Robin.Prompt:input_type -> services.PromptRequest
	6,  // 8: services.Robin.RawPrompt:input_type -> services.RawPromptRequest
	7,  // 9: services.Robin.Summarize:input_type -> services.SummarizeRequest
	1,  // 10: services.Robin.ChatInCodeHost:output_type -> services.ChatInCodeHostReply
	3,  // 11: services.Robin.Explain:output_type -> services.ExplainReply
	5,  // 12: services.Robin.Prompt:output_type -> services.PromptReply
	5,  // 13: services.Robin.RawPrompt:output_type -> services.PromptReply
	8,  // 14: services.Robin.Summarize:output_type -> services.SummarizeReply
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_services_robin_proto_init() }
func file_services_robin_proto_init() {
	if File_services_robin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_robin_proto_rawDesc), len(file_services_robin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_robin_proto_goTypes,
		DependencyIndexes: file_services_robin_proto_depIdxs,
		MessageInfos:      file_services_robin_proto_msgTypes,
	}.Build()
	File_services_robin_proto = out.File
	file_services_robin_proto_goTypes = nil
	file_services_robin_proto_depIdxs = nil
}
