// Copyright 2022 Explore.dev Unipessoal Lda. All Rights Reserved.
// Use of this source code is governed by a license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: services/semantic.proto

package services

import (
	entities "github.com/reviewpad/api/go/entities"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSymbolsRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Uri           string                    `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	CommitId      string                    `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	BlobId        string                    `protobuf:"bytes,3,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	Filepath      string                    `protobuf:"bytes,4,opt,name=filepath,proto3" json:"filepath,omitempty"`
	Blob          []byte                    `protobuf:"bytes,5,opt,name=blob,proto3" json:"blob,omitempty"`
	Diff          *entities.ResolveFileDiff `protobuf:"bytes,6,opt,name=diff,proto3" json:"diff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolsRequest) Reset() {
	*x = GetSymbolsRequest{}
	mi := &file_services_semantic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolsRequest) ProtoMessage() {}

func (x *GetSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_semantic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolsRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_services_semantic_proto_rawDescGZIP(), []int{0}
}

func (x *GetSymbolsRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *GetSymbolsRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *GetSymbolsRequest) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *GetSymbolsRequest) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *GetSymbolsRequest) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *GetSymbolsRequest) GetDiff() *entities.ResolveFileDiff {
	if x != nil {
		return x.Diff
	}
	return nil
}

type GetSymbolsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       *entities.Symbols      `protobuf:"bytes,1,opt,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolsReply) Reset() {
	*x = GetSymbolsReply{}
	mi := &file_services_semantic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolsReply) ProtoMessage() {}

func (x *GetSymbolsReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_semantic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolsReply.ProtoReflect.Descriptor instead.
func (*GetSymbolsReply) Descriptor() ([]byte, []int) {
	return file_services_semantic_proto_rawDescGZIP(), []int{1}
}

func (x *GetSymbolsReply) GetSymbols() *entities.Symbols {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_services_semantic_proto protoreflect.FileDescriptor

const file_services_semantic_proto_rawDesc = "" +
	"\n" +
	"\x17services/semantic.proto\x12\bservices\x1a\x17entities/language.proto\x1a\x13entities/diff.proto\"\xba\x01\n" +
	"\x11GetSymbolsRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\x12\x17\n" +
	"\ablob_id\x18\x03 \x01(\tR\x06blobId\x12\x1a\n" +
	"\bfilepath\x18\x04 \x01(\tR\bfilepath\x12\x12\n" +
	"\x04blob\x18\x05 \x01(\fR\x04blob\x12-\n" +
	"\x04diff\x18\x06 \x01(\v2\x19.entities.ResolveFileDiffR\x04diff\">\n" +
	"\x0fGetSymbolsReply\x12+\n" +
	"\asymbols\x18\x01 \x01(\v2\x11.entities.SymbolsR\asymbols2R\n" +
	"\bSemantic\x12F\n" +
	"\n" +
	"GetSymbols\x12\x1b.services.GetSymbolsRequest\x1a\x19.services.GetSymbolsReply\"\x00B&Z$github.com/reviewpad/api/go/servicesb\x06proto3"

var (
	file_services_semantic_proto_rawDescOnce sync.Once
	file_services_semantic_proto_rawDescData []byte
)

func file_services_semantic_proto_rawDescGZIP() []byte {
	file_services_semantic_proto_rawDescOnce.Do(func() {
		file_services_semantic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_semantic_proto_rawDesc), len(file_services_semantic_proto_rawDesc)))
	})
	return file_services_semantic_proto_rawDescData
}

var file_services_semantic_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_semantic_proto_goTypes = []any{
	(*GetSymbolsRequest)(nil),        // 0: services.GetSymbolsRequest
	(*GetSymbolsReply)(nil),          // 1: services.GetSymbolsReply
	(*entities.ResolveFileDiff)(nil), // 2: entities.ResolveFileDiff
	(*entities.Symbols)(nil),         // 3: entities.Symbols
}
var file_services_semantic_proto_depIdxs = []int32{
	2, // 0: services.GetSymbolsRequest.diff:type_name -> entities.ResolveFileDiff
	3, // 1: services.GetSymbolsReply.symbols:type_name -> entities.Symbols
	0, // 2: services.Semantic.GetSymbols:input_type -> services.GetSymbolsRequest
	1, // 3: services.Semantic.GetSymbols:output_type -> services.GetSymbolsReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_semantic_proto_init() }
func file_services_semantic_proto_init() {
	if File_services_semantic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_semantic_proto_rawDesc), len(file_services_semantic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_semantic_proto_goTypes,
		DependencyIndexes: file_services_semantic_proto_depIdxs,
		MessageInfos:      file_services_semantic_proto_msgTypes,
	}.Build()
	File_services_semantic_proto = out.File
	file_services_semantic_proto_goTypes = nil
	file_services_semantic_proto_depIdxs = nil
}
